package com.xxx.collect.base.model;

import java.util.ArrayList;
import java.util.List;

public class ErrorLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public ErrorLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCurDateIsNull() {
            addCriterion("CUR_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCurDateIsNotNull() {
            addCriterion("CUR_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCurDateEqualTo(String value) {
            addCriterion("CUR_DATE =", value, "curDate");
            return (Criteria) this;
        }

        public Criteria andCurDateNotEqualTo(String value) {
            addCriterion("CUR_DATE <>", value, "curDate");
            return (Criteria) this;
        }

        public Criteria andCurDateGreaterThan(String value) {
            addCriterion("CUR_DATE >", value, "curDate");
            return (Criteria) this;
        }

        public Criteria andCurDateGreaterThanOrEqualTo(String value) {
            addCriterion("CUR_DATE >=", value, "curDate");
            return (Criteria) this;
        }

        public Criteria andCurDateLessThan(String value) {
            addCriterion("CUR_DATE <", value, "curDate");
            return (Criteria) this;
        }

        public Criteria andCurDateLessThanOrEqualTo(String value) {
            addCriterion("CUR_DATE <=", value, "curDate");
            return (Criteria) this;
        }

        public Criteria andCurDateLike(String value) {
            addCriterion("CUR_DATE like", value, "curDate");
            return (Criteria) this;
        }

        public Criteria andCurDateNotLike(String value) {
            addCriterion("CUR_DATE not like", value, "curDate");
            return (Criteria) this;
        }

        public Criteria andCurDateIn(List<String> values) {
            addCriterion("CUR_DATE in", values, "curDate");
            return (Criteria) this;
        }

        public Criteria andCurDateNotIn(List<String> values) {
            addCriterion("CUR_DATE not in", values, "curDate");
            return (Criteria) this;
        }

        public Criteria andCurDateBetween(String value1, String value2) {
            addCriterion("CUR_DATE between", value1, value2, "curDate");
            return (Criteria) this;
        }

        public Criteria andCurDateNotBetween(String value1, String value2) {
            addCriterion("CUR_DATE not between", value1, value2, "curDate");
            return (Criteria) this;
        }

        public Criteria andTaskNameIsNull() {
            addCriterion("TASK_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTaskNameIsNotNull() {
            addCriterion("TASK_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTaskNameEqualTo(String value) {
            addCriterion("TASK_NAME =", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotEqualTo(String value) {
            addCriterion("TASK_NAME <>", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameGreaterThan(String value) {
            addCriterion("TASK_NAME >", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameGreaterThanOrEqualTo(String value) {
            addCriterion("TASK_NAME >=", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameLessThan(String value) {
            addCriterion("TASK_NAME <", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameLessThanOrEqualTo(String value) {
            addCriterion("TASK_NAME <=", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameLike(String value) {
            addCriterion("TASK_NAME like", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotLike(String value) {
            addCriterion("TASK_NAME not like", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameIn(List<String> values) {
            addCriterion("TASK_NAME in", values, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotIn(List<String> values) {
            addCriterion("TASK_NAME not in", values, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameBetween(String value1, String value2) {
            addCriterion("TASK_NAME between", value1, value2, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotBetween(String value1, String value2) {
            addCriterion("TASK_NAME not between", value1, value2, "taskName");
            return (Criteria) this;
        }

        public Criteria andInfoIdIsNull() {
            addCriterion("INFO_ID is null");
            return (Criteria) this;
        }

        public Criteria andInfoIdIsNotNull() {
            addCriterion("INFO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInfoIdEqualTo(String value) {
            addCriterion("INFO_ID =", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotEqualTo(String value) {
            addCriterion("INFO_ID <>", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdGreaterThan(String value) {
            addCriterion("INFO_ID >", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdGreaterThanOrEqualTo(String value) {
            addCriterion("INFO_ID >=", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdLessThan(String value) {
            addCriterion("INFO_ID <", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdLessThanOrEqualTo(String value) {
            addCriterion("INFO_ID <=", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdLike(String value) {
            addCriterion("INFO_ID like", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotLike(String value) {
            addCriterion("INFO_ID not like", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdIn(List<String> values) {
            addCriterion("INFO_ID in", values, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotIn(List<String> values) {
            addCriterion("INFO_ID not in", values, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdBetween(String value1, String value2) {
            addCriterion("INFO_ID between", value1, value2, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotBetween(String value1, String value2) {
            addCriterion("INFO_ID not between", value1, value2, "infoId");
            return (Criteria) this;
        }

        public Criteria andLogDevIsNull() {
            addCriterion("LOG_DEV is null");
            return (Criteria) this;
        }

        public Criteria andLogDevIsNotNull() {
            addCriterion("LOG_DEV is not null");
            return (Criteria) this;
        }

        public Criteria andLogDevEqualTo(String value) {
            addCriterion("LOG_DEV =", value, "logDev");
            return (Criteria) this;
        }

        public Criteria andLogDevNotEqualTo(String value) {
            addCriterion("LOG_DEV <>", value, "logDev");
            return (Criteria) this;
        }

        public Criteria andLogDevGreaterThan(String value) {
            addCriterion("LOG_DEV >", value, "logDev");
            return (Criteria) this;
        }

        public Criteria andLogDevGreaterThanOrEqualTo(String value) {
            addCriterion("LOG_DEV >=", value, "logDev");
            return (Criteria) this;
        }

        public Criteria andLogDevLessThan(String value) {
            addCriterion("LOG_DEV <", value, "logDev");
            return (Criteria) this;
        }

        public Criteria andLogDevLessThanOrEqualTo(String value) {
            addCriterion("LOG_DEV <=", value, "logDev");
            return (Criteria) this;
        }

        public Criteria andLogDevLike(String value) {
            addCriterion("LOG_DEV like", value, "logDev");
            return (Criteria) this;
        }

        public Criteria andLogDevNotLike(String value) {
            addCriterion("LOG_DEV not like", value, "logDev");
            return (Criteria) this;
        }

        public Criteria andLogDevIn(List<String> values) {
            addCriterion("LOG_DEV in", values, "logDev");
            return (Criteria) this;
        }

        public Criteria andLogDevNotIn(List<String> values) {
            addCriterion("LOG_DEV not in", values, "logDev");
            return (Criteria) this;
        }

        public Criteria andLogDevBetween(String value1, String value2) {
            addCriterion("LOG_DEV between", value1, value2, "logDev");
            return (Criteria) this;
        }

        public Criteria andLogDevNotBetween(String value1, String value2) {
            addCriterion("LOG_DEV not between", value1, value2, "logDev");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table error_log
     *
     * @mbggenerated do_not_delete_during_merge Fri Feb 17 11:19:29 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}