package com.xxx.collect.base.model;

import java.io.Serializable;
import java.util.Date;

public class LangInfo extends LangInfoKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lang_info.type
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lang_info.is_trans
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private Boolean isTrans;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lang_info.translate_model
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private Integer translateModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lang_info.is_audit
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private Boolean isAudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lang_info.create_time
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lang_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lang_info.type
     *
     * @return the value of lang_info.type
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lang_info.type
     *
     * @param type the value for lang_info.type
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lang_info.is_trans
     *
     * @return the value of lang_info.is_trans
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public Boolean getIsTrans() {
        return isTrans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lang_info.is_trans
     *
     * @param isTrans the value for lang_info.is_trans
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setIsTrans(Boolean isTrans) {
        this.isTrans = isTrans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lang_info.translate_model
     *
     * @return the value of lang_info.translate_model
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public Integer getTranslateModel() {
        return translateModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lang_info.translate_model
     *
     * @param translateModel the value for lang_info.translate_model
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setTranslateModel(Integer translateModel) {
        this.translateModel = translateModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lang_info.is_audit
     *
     * @return the value of lang_info.is_audit
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public Boolean getIsAudit() {
        return isAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lang_info.is_audit
     *
     * @param isAudit the value for lang_info.is_audit
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setIsAudit(Boolean isAudit) {
        this.isAudit = isAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lang_info.create_time
     *
     * @return the value of lang_info.create_time
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lang_info.create_time
     *
     * @param createTime the value for lang_info.create_time
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}