package com.xxx.collect.base.model;

import java.io.Serializable;
import java.util.Date;

public class SpiderHtmlStore implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_html_store.url
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_html_store.create_time
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_html_store.html
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private String html;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spider_html_store
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_html_store.url
     *
     * @return the value of spider_html_store.url
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_html_store.url
     *
     * @param url the value for spider_html_store.url
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_html_store.create_time
     *
     * @return the value of spider_html_store.create_time
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_html_store.create_time
     *
     * @param createTime the value for spider_html_store.create_time
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_html_store.html
     *
     * @return the value of spider_html_store.html
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public String getHtml() {
        return html;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_html_store.html
     *
     * @param html the value for spider_html_store.html
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setHtml(String html) {
        this.html = html == null ? null : html.trim();
    }
}