package com.xxx.collect.base.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SpiderRescInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spider_resc_info
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spider_resc_info
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spider_resc_info
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_resc_info
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public SpiderRescInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_resc_info
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_resc_info
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_resc_info
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_resc_info
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_resc_info
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_resc_info
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_resc_info
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_resc_info
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_resc_info
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_resc_info
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table spider_resc_info
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSiteIsNull() {
            addCriterion("site is null");
            return (Criteria) this;
        }

        public Criteria andSiteIsNotNull() {
            addCriterion("site is not null");
            return (Criteria) this;
        }

        public Criteria andSiteEqualTo(String value) {
            addCriterion("site =", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteNotEqualTo(String value) {
            addCriterion("site <>", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteGreaterThan(String value) {
            addCriterion("site >", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteGreaterThanOrEqualTo(String value) {
            addCriterion("site >=", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteLessThan(String value) {
            addCriterion("site <", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteLessThanOrEqualTo(String value) {
            addCriterion("site <=", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteLike(String value) {
            addCriterion("site like", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteNotLike(String value) {
            addCriterion("site not like", value, "site");
            return (Criteria) this;
        }

        public Criteria andSiteIn(List<String> values) {
            addCriterion("site in", values, "site");
            return (Criteria) this;
        }

        public Criteria andSiteNotIn(List<String> values) {
            addCriterion("site not in", values, "site");
            return (Criteria) this;
        }

        public Criteria andSiteBetween(String value1, String value2) {
            addCriterion("site between", value1, value2, "site");
            return (Criteria) this;
        }

        public Criteria andSiteNotBetween(String value1, String value2) {
            addCriterion("site not between", value1, value2, "site");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andPicIsNull() {
            addCriterion("pic is null");
            return (Criteria) this;
        }

        public Criteria andPicIsNotNull() {
            addCriterion("pic is not null");
            return (Criteria) this;
        }

        public Criteria andPicEqualTo(String value) {
            addCriterion("pic =", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicNotEqualTo(String value) {
            addCriterion("pic <>", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicGreaterThan(String value) {
            addCriterion("pic >", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicGreaterThanOrEqualTo(String value) {
            addCriterion("pic >=", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicLessThan(String value) {
            addCriterion("pic <", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicLessThanOrEqualTo(String value) {
            addCriterion("pic <=", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicLike(String value) {
            addCriterion("pic like", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicNotLike(String value) {
            addCriterion("pic not like", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicIn(List<String> values) {
            addCriterion("pic in", values, "pic");
            return (Criteria) this;
        }

        public Criteria andPicNotIn(List<String> values) {
            addCriterion("pic not in", values, "pic");
            return (Criteria) this;
        }

        public Criteria andPicBetween(String value1, String value2) {
            addCriterion("pic between", value1, value2, "pic");
            return (Criteria) this;
        }

        public Criteria andPicNotBetween(String value1, String value2) {
            addCriterion("pic not between", value1, value2, "pic");
            return (Criteria) this;
        }

        public Criteria andPicFileIdIsNull() {
            addCriterion("pic_file_id is null");
            return (Criteria) this;
        }

        public Criteria andPicFileIdIsNotNull() {
            addCriterion("pic_file_id is not null");
            return (Criteria) this;
        }

        public Criteria andPicFileIdEqualTo(Integer value) {
            addCriterion("pic_file_id =", value, "picFileId");
            return (Criteria) this;
        }

        public Criteria andPicFileIdNotEqualTo(Integer value) {
            addCriterion("pic_file_id <>", value, "picFileId");
            return (Criteria) this;
        }

        public Criteria andPicFileIdGreaterThan(Integer value) {
            addCriterion("pic_file_id >", value, "picFileId");
            return (Criteria) this;
        }

        public Criteria andPicFileIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("pic_file_id >=", value, "picFileId");
            return (Criteria) this;
        }

        public Criteria andPicFileIdLessThan(Integer value) {
            addCriterion("pic_file_id <", value, "picFileId");
            return (Criteria) this;
        }

        public Criteria andPicFileIdLessThanOrEqualTo(Integer value) {
            addCriterion("pic_file_id <=", value, "picFileId");
            return (Criteria) this;
        }

        public Criteria andPicFileIdIn(List<Integer> values) {
            addCriterion("pic_file_id in", values, "picFileId");
            return (Criteria) this;
        }

        public Criteria andPicFileIdNotIn(List<Integer> values) {
            addCriterion("pic_file_id not in", values, "picFileId");
            return (Criteria) this;
        }

        public Criteria andPicFileIdBetween(Integer value1, Integer value2) {
            addCriterion("pic_file_id between", value1, value2, "picFileId");
            return (Criteria) this;
        }

        public Criteria andPicFileIdNotBetween(Integer value1, Integer value2) {
            addCriterion("pic_file_id not between", value1, value2, "picFileId");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andTags1IsNull() {
            addCriterion("tags1 is null");
            return (Criteria) this;
        }

        public Criteria andTags1IsNotNull() {
            addCriterion("tags1 is not null");
            return (Criteria) this;
        }

        public Criteria andTags1EqualTo(String value) {
            addCriterion("tags1 =", value, "tags1");
            return (Criteria) this;
        }

        public Criteria andTags1NotEqualTo(String value) {
            addCriterion("tags1 <>", value, "tags1");
            return (Criteria) this;
        }

        public Criteria andTags1GreaterThan(String value) {
            addCriterion("tags1 >", value, "tags1");
            return (Criteria) this;
        }

        public Criteria andTags1GreaterThanOrEqualTo(String value) {
            addCriterion("tags1 >=", value, "tags1");
            return (Criteria) this;
        }

        public Criteria andTags1LessThan(String value) {
            addCriterion("tags1 <", value, "tags1");
            return (Criteria) this;
        }

        public Criteria andTags1LessThanOrEqualTo(String value) {
            addCriterion("tags1 <=", value, "tags1");
            return (Criteria) this;
        }

        public Criteria andTags1Like(String value) {
            addCriterion("tags1 like", value, "tags1");
            return (Criteria) this;
        }

        public Criteria andTags1NotLike(String value) {
            addCriterion("tags1 not like", value, "tags1");
            return (Criteria) this;
        }

        public Criteria andTags1In(List<String> values) {
            addCriterion("tags1 in", values, "tags1");
            return (Criteria) this;
        }

        public Criteria andTags1NotIn(List<String> values) {
            addCriterion("tags1 not in", values, "tags1");
            return (Criteria) this;
        }

        public Criteria andTags1Between(String value1, String value2) {
            addCriterion("tags1 between", value1, value2, "tags1");
            return (Criteria) this;
        }

        public Criteria andTags1NotBetween(String value1, String value2) {
            addCriterion("tags1 not between", value1, value2, "tags1");
            return (Criteria) this;
        }

        public Criteria andTags2IsNull() {
            addCriterion("tags2 is null");
            return (Criteria) this;
        }

        public Criteria andTags2IsNotNull() {
            addCriterion("tags2 is not null");
            return (Criteria) this;
        }

        public Criteria andTags2EqualTo(String value) {
            addCriterion("tags2 =", value, "tags2");
            return (Criteria) this;
        }

        public Criteria andTags2NotEqualTo(String value) {
            addCriterion("tags2 <>", value, "tags2");
            return (Criteria) this;
        }

        public Criteria andTags2GreaterThan(String value) {
            addCriterion("tags2 >", value, "tags2");
            return (Criteria) this;
        }

        public Criteria andTags2GreaterThanOrEqualTo(String value) {
            addCriterion("tags2 >=", value, "tags2");
            return (Criteria) this;
        }

        public Criteria andTags2LessThan(String value) {
            addCriterion("tags2 <", value, "tags2");
            return (Criteria) this;
        }

        public Criteria andTags2LessThanOrEqualTo(String value) {
            addCriterion("tags2 <=", value, "tags2");
            return (Criteria) this;
        }

        public Criteria andTags2Like(String value) {
            addCriterion("tags2 like", value, "tags2");
            return (Criteria) this;
        }

        public Criteria andTags2NotLike(String value) {
            addCriterion("tags2 not like", value, "tags2");
            return (Criteria) this;
        }

        public Criteria andTags2In(List<String> values) {
            addCriterion("tags2 in", values, "tags2");
            return (Criteria) this;
        }

        public Criteria andTags2NotIn(List<String> values) {
            addCriterion("tags2 not in", values, "tags2");
            return (Criteria) this;
        }

        public Criteria andTags2Between(String value1, String value2) {
            addCriterion("tags2 between", value1, value2, "tags2");
            return (Criteria) this;
        }

        public Criteria andTags2NotBetween(String value1, String value2) {
            addCriterion("tags2 not between", value1, value2, "tags2");
            return (Criteria) this;
        }

        public Criteria andTags3IsNull() {
            addCriterion("tags3 is null");
            return (Criteria) this;
        }

        public Criteria andTags3IsNotNull() {
            addCriterion("tags3 is not null");
            return (Criteria) this;
        }

        public Criteria andTags3EqualTo(String value) {
            addCriterion("tags3 =", value, "tags3");
            return (Criteria) this;
        }

        public Criteria andTags3NotEqualTo(String value) {
            addCriterion("tags3 <>", value, "tags3");
            return (Criteria) this;
        }

        public Criteria andTags3GreaterThan(String value) {
            addCriterion("tags3 >", value, "tags3");
            return (Criteria) this;
        }

        public Criteria andTags3GreaterThanOrEqualTo(String value) {
            addCriterion("tags3 >=", value, "tags3");
            return (Criteria) this;
        }

        public Criteria andTags3LessThan(String value) {
            addCriterion("tags3 <", value, "tags3");
            return (Criteria) this;
        }

        public Criteria andTags3LessThanOrEqualTo(String value) {
            addCriterion("tags3 <=", value, "tags3");
            return (Criteria) this;
        }

        public Criteria andTags3Like(String value) {
            addCriterion("tags3 like", value, "tags3");
            return (Criteria) this;
        }

        public Criteria andTags3NotLike(String value) {
            addCriterion("tags3 not like", value, "tags3");
            return (Criteria) this;
        }

        public Criteria andTags3In(List<String> values) {
            addCriterion("tags3 in", values, "tags3");
            return (Criteria) this;
        }

        public Criteria andTags3NotIn(List<String> values) {
            addCriterion("tags3 not in", values, "tags3");
            return (Criteria) this;
        }

        public Criteria andTags3Between(String value1, String value2) {
            addCriterion("tags3 between", value1, value2, "tags3");
            return (Criteria) this;
        }

        public Criteria andTags3NotBetween(String value1, String value2) {
            addCriterion("tags3 not between", value1, value2, "tags3");
            return (Criteria) this;
        }

        public Criteria andTags4IsNull() {
            addCriterion("tags4 is null");
            return (Criteria) this;
        }

        public Criteria andTags4IsNotNull() {
            addCriterion("tags4 is not null");
            return (Criteria) this;
        }

        public Criteria andTags4EqualTo(String value) {
            addCriterion("tags4 =", value, "tags4");
            return (Criteria) this;
        }

        public Criteria andTags4NotEqualTo(String value) {
            addCriterion("tags4 <>", value, "tags4");
            return (Criteria) this;
        }

        public Criteria andTags4GreaterThan(String value) {
            addCriterion("tags4 >", value, "tags4");
            return (Criteria) this;
        }

        public Criteria andTags4GreaterThanOrEqualTo(String value) {
            addCriterion("tags4 >=", value, "tags4");
            return (Criteria) this;
        }

        public Criteria andTags4LessThan(String value) {
            addCriterion("tags4 <", value, "tags4");
            return (Criteria) this;
        }

        public Criteria andTags4LessThanOrEqualTo(String value) {
            addCriterion("tags4 <=", value, "tags4");
            return (Criteria) this;
        }

        public Criteria andTags4Like(String value) {
            addCriterion("tags4 like", value, "tags4");
            return (Criteria) this;
        }

        public Criteria andTags4NotLike(String value) {
            addCriterion("tags4 not like", value, "tags4");
            return (Criteria) this;
        }

        public Criteria andTags4In(List<String> values) {
            addCriterion("tags4 in", values, "tags4");
            return (Criteria) this;
        }

        public Criteria andTags4NotIn(List<String> values) {
            addCriterion("tags4 not in", values, "tags4");
            return (Criteria) this;
        }

        public Criteria andTags4Between(String value1, String value2) {
            addCriterion("tags4 between", value1, value2, "tags4");
            return (Criteria) this;
        }

        public Criteria andTags4NotBetween(String value1, String value2) {
            addCriterion("tags4 not between", value1, value2, "tags4");
            return (Criteria) this;
        }

        public Criteria andCatIsNull() {
            addCriterion("cat is null");
            return (Criteria) this;
        }

        public Criteria andCatIsNotNull() {
            addCriterion("cat is not null");
            return (Criteria) this;
        }

        public Criteria andCatEqualTo(String value) {
            addCriterion("cat =", value, "cat");
            return (Criteria) this;
        }

        public Criteria andCatNotEqualTo(String value) {
            addCriterion("cat <>", value, "cat");
            return (Criteria) this;
        }

        public Criteria andCatGreaterThan(String value) {
            addCriterion("cat >", value, "cat");
            return (Criteria) this;
        }

        public Criteria andCatGreaterThanOrEqualTo(String value) {
            addCriterion("cat >=", value, "cat");
            return (Criteria) this;
        }

        public Criteria andCatLessThan(String value) {
            addCriterion("cat <", value, "cat");
            return (Criteria) this;
        }

        public Criteria andCatLessThanOrEqualTo(String value) {
            addCriterion("cat <=", value, "cat");
            return (Criteria) this;
        }

        public Criteria andCatLike(String value) {
            addCriterion("cat like", value, "cat");
            return (Criteria) this;
        }

        public Criteria andCatNotLike(String value) {
            addCriterion("cat not like", value, "cat");
            return (Criteria) this;
        }

        public Criteria andCatIn(List<String> values) {
            addCriterion("cat in", values, "cat");
            return (Criteria) this;
        }

        public Criteria andCatNotIn(List<String> values) {
            addCriterion("cat not in", values, "cat");
            return (Criteria) this;
        }

        public Criteria andCatBetween(String value1, String value2) {
            addCriterion("cat between", value1, value2, "cat");
            return (Criteria) this;
        }

        public Criteria andCatNotBetween(String value1, String value2) {
            addCriterion("cat not between", value1, value2, "cat");
            return (Criteria) this;
        }

        public Criteria andSubCatIsNull() {
            addCriterion("sub_cat is null");
            return (Criteria) this;
        }

        public Criteria andSubCatIsNotNull() {
            addCriterion("sub_cat is not null");
            return (Criteria) this;
        }

        public Criteria andSubCatEqualTo(String value) {
            addCriterion("sub_cat =", value, "subCat");
            return (Criteria) this;
        }

        public Criteria andSubCatNotEqualTo(String value) {
            addCriterion("sub_cat <>", value, "subCat");
            return (Criteria) this;
        }

        public Criteria andSubCatGreaterThan(String value) {
            addCriterion("sub_cat >", value, "subCat");
            return (Criteria) this;
        }

        public Criteria andSubCatGreaterThanOrEqualTo(String value) {
            addCriterion("sub_cat >=", value, "subCat");
            return (Criteria) this;
        }

        public Criteria andSubCatLessThan(String value) {
            addCriterion("sub_cat <", value, "subCat");
            return (Criteria) this;
        }

        public Criteria andSubCatLessThanOrEqualTo(String value) {
            addCriterion("sub_cat <=", value, "subCat");
            return (Criteria) this;
        }

        public Criteria andSubCatLike(String value) {
            addCriterion("sub_cat like", value, "subCat");
            return (Criteria) this;
        }

        public Criteria andSubCatNotLike(String value) {
            addCriterion("sub_cat not like", value, "subCat");
            return (Criteria) this;
        }

        public Criteria andSubCatIn(List<String> values) {
            addCriterion("sub_cat in", values, "subCat");
            return (Criteria) this;
        }

        public Criteria andSubCatNotIn(List<String> values) {
            addCriterion("sub_cat not in", values, "subCat");
            return (Criteria) this;
        }

        public Criteria andSubCatBetween(String value1, String value2) {
            addCriterion("sub_cat between", value1, value2, "subCat");
            return (Criteria) this;
        }

        public Criteria andSubCatNotBetween(String value1, String value2) {
            addCriterion("sub_cat not between", value1, value2, "subCat");
            return (Criteria) this;
        }

        public Criteria andSubCatLv3IsNull() {
            addCriterion("sub_cat_lv3 is null");
            return (Criteria) this;
        }

        public Criteria andSubCatLv3IsNotNull() {
            addCriterion("sub_cat_lv3 is not null");
            return (Criteria) this;
        }

        public Criteria andSubCatLv3EqualTo(String value) {
            addCriterion("sub_cat_lv3 =", value, "subCatLv3");
            return (Criteria) this;
        }

        public Criteria andSubCatLv3NotEqualTo(String value) {
            addCriterion("sub_cat_lv3 <>", value, "subCatLv3");
            return (Criteria) this;
        }

        public Criteria andSubCatLv3GreaterThan(String value) {
            addCriterion("sub_cat_lv3 >", value, "subCatLv3");
            return (Criteria) this;
        }

        public Criteria andSubCatLv3GreaterThanOrEqualTo(String value) {
            addCriterion("sub_cat_lv3 >=", value, "subCatLv3");
            return (Criteria) this;
        }

        public Criteria andSubCatLv3LessThan(String value) {
            addCriterion("sub_cat_lv3 <", value, "subCatLv3");
            return (Criteria) this;
        }

        public Criteria andSubCatLv3LessThanOrEqualTo(String value) {
            addCriterion("sub_cat_lv3 <=", value, "subCatLv3");
            return (Criteria) this;
        }

        public Criteria andSubCatLv3Like(String value) {
            addCriterion("sub_cat_lv3 like", value, "subCatLv3");
            return (Criteria) this;
        }

        public Criteria andSubCatLv3NotLike(String value) {
            addCriterion("sub_cat_lv3 not like", value, "subCatLv3");
            return (Criteria) this;
        }

        public Criteria andSubCatLv3In(List<String> values) {
            addCriterion("sub_cat_lv3 in", values, "subCatLv3");
            return (Criteria) this;
        }

        public Criteria andSubCatLv3NotIn(List<String> values) {
            addCriterion("sub_cat_lv3 not in", values, "subCatLv3");
            return (Criteria) this;
        }

        public Criteria andSubCatLv3Between(String value1, String value2) {
            addCriterion("sub_cat_lv3 between", value1, value2, "subCatLv3");
            return (Criteria) this;
        }

        public Criteria andSubCatLv3NotBetween(String value1, String value2) {
            addCriterion("sub_cat_lv3 not between", value1, value2, "subCatLv3");
            return (Criteria) this;
        }

        public Criteria andSubCatLv4IsNull() {
            addCriterion("sub_cat_lv4 is null");
            return (Criteria) this;
        }

        public Criteria andSubCatLv4IsNotNull() {
            addCriterion("sub_cat_lv4 is not null");
            return (Criteria) this;
        }

        public Criteria andSubCatLv4EqualTo(String value) {
            addCriterion("sub_cat_lv4 =", value, "subCatLv4");
            return (Criteria) this;
        }

        public Criteria andSubCatLv4NotEqualTo(String value) {
            addCriterion("sub_cat_lv4 <>", value, "subCatLv4");
            return (Criteria) this;
        }

        public Criteria andSubCatLv4GreaterThan(String value) {
            addCriterion("sub_cat_lv4 >", value, "subCatLv4");
            return (Criteria) this;
        }

        public Criteria andSubCatLv4GreaterThanOrEqualTo(String value) {
            addCriterion("sub_cat_lv4 >=", value, "subCatLv4");
            return (Criteria) this;
        }

        public Criteria andSubCatLv4LessThan(String value) {
            addCriterion("sub_cat_lv4 <", value, "subCatLv4");
            return (Criteria) this;
        }

        public Criteria andSubCatLv4LessThanOrEqualTo(String value) {
            addCriterion("sub_cat_lv4 <=", value, "subCatLv4");
            return (Criteria) this;
        }

        public Criteria andSubCatLv4Like(String value) {
            addCriterion("sub_cat_lv4 like", value, "subCatLv4");
            return (Criteria) this;
        }

        public Criteria andSubCatLv4NotLike(String value) {
            addCriterion("sub_cat_lv4 not like", value, "subCatLv4");
            return (Criteria) this;
        }

        public Criteria andSubCatLv4In(List<String> values) {
            addCriterion("sub_cat_lv4 in", values, "subCatLv4");
            return (Criteria) this;
        }

        public Criteria andSubCatLv4NotIn(List<String> values) {
            addCriterion("sub_cat_lv4 not in", values, "subCatLv4");
            return (Criteria) this;
        }

        public Criteria andSubCatLv4Between(String value1, String value2) {
            addCriterion("sub_cat_lv4 between", value1, value2, "subCatLv4");
            return (Criteria) this;
        }

        public Criteria andSubCatLv4NotBetween(String value1, String value2) {
            addCriterion("sub_cat_lv4 not between", value1, value2, "subCatLv4");
            return (Criteria) this;
        }

        public Criteria andBuyCntIsNull() {
            addCriterion("buy_cnt is null");
            return (Criteria) this;
        }

        public Criteria andBuyCntIsNotNull() {
            addCriterion("buy_cnt is not null");
            return (Criteria) this;
        }

        public Criteria andBuyCntEqualTo(Integer value) {
            addCriterion("buy_cnt =", value, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andBuyCntNotEqualTo(Integer value) {
            addCriterion("buy_cnt <>", value, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andBuyCntGreaterThan(Integer value) {
            addCriterion("buy_cnt >", value, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andBuyCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("buy_cnt >=", value, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andBuyCntLessThan(Integer value) {
            addCriterion("buy_cnt <", value, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andBuyCntLessThanOrEqualTo(Integer value) {
            addCriterion("buy_cnt <=", value, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andBuyCntIn(List<Integer> values) {
            addCriterion("buy_cnt in", values, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andBuyCntNotIn(List<Integer> values) {
            addCriterion("buy_cnt not in", values, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andBuyCntBetween(Integer value1, Integer value2) {
            addCriterion("buy_cnt between", value1, value2, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andBuyCntNotBetween(Integer value1, Integer value2) {
            addCriterion("buy_cnt not between", value1, value2, "buyCnt");
            return (Criteria) this;
        }

        public Criteria andGoodCntIsNull() {
            addCriterion("good_cnt is null");
            return (Criteria) this;
        }

        public Criteria andGoodCntIsNotNull() {
            addCriterion("good_cnt is not null");
            return (Criteria) this;
        }

        public Criteria andGoodCntEqualTo(Integer value) {
            addCriterion("good_cnt =", value, "goodCnt");
            return (Criteria) this;
        }

        public Criteria andGoodCntNotEqualTo(Integer value) {
            addCriterion("good_cnt <>", value, "goodCnt");
            return (Criteria) this;
        }

        public Criteria andGoodCntGreaterThan(Integer value) {
            addCriterion("good_cnt >", value, "goodCnt");
            return (Criteria) this;
        }

        public Criteria andGoodCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("good_cnt >=", value, "goodCnt");
            return (Criteria) this;
        }

        public Criteria andGoodCntLessThan(Integer value) {
            addCriterion("good_cnt <", value, "goodCnt");
            return (Criteria) this;
        }

        public Criteria andGoodCntLessThanOrEqualTo(Integer value) {
            addCriterion("good_cnt <=", value, "goodCnt");
            return (Criteria) this;
        }

        public Criteria andGoodCntIn(List<Integer> values) {
            addCriterion("good_cnt in", values, "goodCnt");
            return (Criteria) this;
        }

        public Criteria andGoodCntNotIn(List<Integer> values) {
            addCriterion("good_cnt not in", values, "goodCnt");
            return (Criteria) this;
        }

        public Criteria andGoodCntBetween(Integer value1, Integer value2) {
            addCriterion("good_cnt between", value1, value2, "goodCnt");
            return (Criteria) this;
        }

        public Criteria andGoodCntNotBetween(Integer value1, Integer value2) {
            addCriterion("good_cnt not between", value1, value2, "goodCnt");
            return (Criteria) this;
        }

        public Criteria andFavCntIsNull() {
            addCriterion("fav_cnt is null");
            return (Criteria) this;
        }

        public Criteria andFavCntIsNotNull() {
            addCriterion("fav_cnt is not null");
            return (Criteria) this;
        }

        public Criteria andFavCntEqualTo(Integer value) {
            addCriterion("fav_cnt =", value, "favCnt");
            return (Criteria) this;
        }

        public Criteria andFavCntNotEqualTo(Integer value) {
            addCriterion("fav_cnt <>", value, "favCnt");
            return (Criteria) this;
        }

        public Criteria andFavCntGreaterThan(Integer value) {
            addCriterion("fav_cnt >", value, "favCnt");
            return (Criteria) this;
        }

        public Criteria andFavCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("fav_cnt >=", value, "favCnt");
            return (Criteria) this;
        }

        public Criteria andFavCntLessThan(Integer value) {
            addCriterion("fav_cnt <", value, "favCnt");
            return (Criteria) this;
        }

        public Criteria andFavCntLessThanOrEqualTo(Integer value) {
            addCriterion("fav_cnt <=", value, "favCnt");
            return (Criteria) this;
        }

        public Criteria andFavCntIn(List<Integer> values) {
            addCriterion("fav_cnt in", values, "favCnt");
            return (Criteria) this;
        }

        public Criteria andFavCntNotIn(List<Integer> values) {
            addCriterion("fav_cnt not in", values, "favCnt");
            return (Criteria) this;
        }

        public Criteria andFavCntBetween(Integer value1, Integer value2) {
            addCriterion("fav_cnt between", value1, value2, "favCnt");
            return (Criteria) this;
        }

        public Criteria andFavCntNotBetween(Integer value1, Integer value2) {
            addCriterion("fav_cnt not between", value1, value2, "favCnt");
            return (Criteria) this;
        }

        public Criteria andCoinIsNull() {
            addCriterion("coin is null");
            return (Criteria) this;
        }

        public Criteria andCoinIsNotNull() {
            addCriterion("coin is not null");
            return (Criteria) this;
        }

        public Criteria andCoinEqualTo(Double value) {
            addCriterion("coin =", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinNotEqualTo(Double value) {
            addCriterion("coin <>", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinGreaterThan(Double value) {
            addCriterion("coin >", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinGreaterThanOrEqualTo(Double value) {
            addCriterion("coin >=", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinLessThan(Double value) {
            addCriterion("coin <", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinLessThanOrEqualTo(Double value) {
            addCriterion("coin <=", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinIn(List<Double> values) {
            addCriterion("coin in", values, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinNotIn(List<Double> values) {
            addCriterion("coin not in", values, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinBetween(Double value1, Double value2) {
            addCriterion("coin between", value1, value2, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinNotBetween(Double value1, Double value2) {
            addCriterion("coin not between", value1, value2, "coin");
            return (Criteria) this;
        }

        public Criteria andUserIsNull() {
            addCriterion("user is null");
            return (Criteria) this;
        }

        public Criteria andUserIsNotNull() {
            addCriterion("user is not null");
            return (Criteria) this;
        }

        public Criteria andUserEqualTo(String value) {
            addCriterion("user =", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotEqualTo(String value) {
            addCriterion("user <>", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserGreaterThan(String value) {
            addCriterion("user >", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserGreaterThanOrEqualTo(String value) {
            addCriterion("user >=", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserLessThan(String value) {
            addCriterion("user <", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserLessThanOrEqualTo(String value) {
            addCriterion("user <=", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserLike(String value) {
            addCriterion("user like", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotLike(String value) {
            addCriterion("user not like", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserIn(List<String> values) {
            addCriterion("user in", values, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotIn(List<String> values) {
            addCriterion("user not in", values, "user");
            return (Criteria) this;
        }

        public Criteria andUserBetween(String value1, String value2) {
            addCriterion("user between", value1, value2, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotBetween(String value1, String value2) {
            addCriterion("user not between", value1, value2, "user");
            return (Criteria) this;
        }

        public Criteria andRescCreateTimeIsNull() {
            addCriterion("resc_create_time is null");
            return (Criteria) this;
        }

        public Criteria andRescCreateTimeIsNotNull() {
            addCriterion("resc_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andRescCreateTimeEqualTo(Date value) {
            addCriterion("resc_create_time =", value, "rescCreateTime");
            return (Criteria) this;
        }

        public Criteria andRescCreateTimeNotEqualTo(Date value) {
            addCriterion("resc_create_time <>", value, "rescCreateTime");
            return (Criteria) this;
        }

        public Criteria andRescCreateTimeGreaterThan(Date value) {
            addCriterion("resc_create_time >", value, "rescCreateTime");
            return (Criteria) this;
        }

        public Criteria andRescCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("resc_create_time >=", value, "rescCreateTime");
            return (Criteria) this;
        }

        public Criteria andRescCreateTimeLessThan(Date value) {
            addCriterion("resc_create_time <", value, "rescCreateTime");
            return (Criteria) this;
        }

        public Criteria andRescCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("resc_create_time <=", value, "rescCreateTime");
            return (Criteria) this;
        }

        public Criteria andRescCreateTimeIn(List<Date> values) {
            addCriterion("resc_create_time in", values, "rescCreateTime");
            return (Criteria) this;
        }

        public Criteria andRescCreateTimeNotIn(List<Date> values) {
            addCriterion("resc_create_time not in", values, "rescCreateTime");
            return (Criteria) this;
        }

        public Criteria andRescCreateTimeBetween(Date value1, Date value2) {
            addCriterion("resc_create_time between", value1, value2, "rescCreateTime");
            return (Criteria) this;
        }

        public Criteria andRescCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("resc_create_time not between", value1, value2, "rescCreateTime");
            return (Criteria) this;
        }

        public Criteria andDownFilePathIsNull() {
            addCriterion("down_file_path is null");
            return (Criteria) this;
        }

        public Criteria andDownFilePathIsNotNull() {
            addCriterion("down_file_path is not null");
            return (Criteria) this;
        }

        public Criteria andDownFilePathEqualTo(String value) {
            addCriterion("down_file_path =", value, "downFilePath");
            return (Criteria) this;
        }

        public Criteria andDownFilePathNotEqualTo(String value) {
            addCriterion("down_file_path <>", value, "downFilePath");
            return (Criteria) this;
        }

        public Criteria andDownFilePathGreaterThan(String value) {
            addCriterion("down_file_path >", value, "downFilePath");
            return (Criteria) this;
        }

        public Criteria andDownFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("down_file_path >=", value, "downFilePath");
            return (Criteria) this;
        }

        public Criteria andDownFilePathLessThan(String value) {
            addCriterion("down_file_path <", value, "downFilePath");
            return (Criteria) this;
        }

        public Criteria andDownFilePathLessThanOrEqualTo(String value) {
            addCriterion("down_file_path <=", value, "downFilePath");
            return (Criteria) this;
        }

        public Criteria andDownFilePathLike(String value) {
            addCriterion("down_file_path like", value, "downFilePath");
            return (Criteria) this;
        }

        public Criteria andDownFilePathNotLike(String value) {
            addCriterion("down_file_path not like", value, "downFilePath");
            return (Criteria) this;
        }

        public Criteria andDownFilePathIn(List<String> values) {
            addCriterion("down_file_path in", values, "downFilePath");
            return (Criteria) this;
        }

        public Criteria andDownFilePathNotIn(List<String> values) {
            addCriterion("down_file_path not in", values, "downFilePath");
            return (Criteria) this;
        }

        public Criteria andDownFilePathBetween(String value1, String value2) {
            addCriterion("down_file_path between", value1, value2, "downFilePath");
            return (Criteria) this;
        }

        public Criteria andDownFilePathNotBetween(String value1, String value2) {
            addCriterion("down_file_path not between", value1, value2, "downFilePath");
            return (Criteria) this;
        }

        public Criteria andFileIdIsNull() {
            addCriterion("file_id is null");
            return (Criteria) this;
        }

        public Criteria andFileIdIsNotNull() {
            addCriterion("file_id is not null");
            return (Criteria) this;
        }

        public Criteria andFileIdEqualTo(Integer value) {
            addCriterion("file_id =", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdNotEqualTo(Integer value) {
            addCriterion("file_id <>", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdGreaterThan(Integer value) {
            addCriterion("file_id >", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("file_id >=", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdLessThan(Integer value) {
            addCriterion("file_id <", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdLessThanOrEqualTo(Integer value) {
            addCriterion("file_id <=", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdIn(List<Integer> values) {
            addCriterion("file_id in", values, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdNotIn(List<Integer> values) {
            addCriterion("file_id not in", values, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdBetween(Integer value1, Integer value2) {
            addCriterion("file_id between", value1, value2, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdNotBetween(Integer value1, Integer value2) {
            addCriterion("file_id not between", value1, value2, "fileId");
            return (Criteria) this;
        }

        public Criteria andPropStr1IsNull() {
            addCriterion("prop_str1 is null");
            return (Criteria) this;
        }

        public Criteria andPropStr1IsNotNull() {
            addCriterion("prop_str1 is not null");
            return (Criteria) this;
        }

        public Criteria andPropStr1EqualTo(String value) {
            addCriterion("prop_str1 =", value, "propStr1");
            return (Criteria) this;
        }

        public Criteria andPropStr1NotEqualTo(String value) {
            addCriterion("prop_str1 <>", value, "propStr1");
            return (Criteria) this;
        }

        public Criteria andPropStr1GreaterThan(String value) {
            addCriterion("prop_str1 >", value, "propStr1");
            return (Criteria) this;
        }

        public Criteria andPropStr1GreaterThanOrEqualTo(String value) {
            addCriterion("prop_str1 >=", value, "propStr1");
            return (Criteria) this;
        }

        public Criteria andPropStr1LessThan(String value) {
            addCriterion("prop_str1 <", value, "propStr1");
            return (Criteria) this;
        }

        public Criteria andPropStr1LessThanOrEqualTo(String value) {
            addCriterion("prop_str1 <=", value, "propStr1");
            return (Criteria) this;
        }

        public Criteria andPropStr1Like(String value) {
            addCriterion("prop_str1 like", value, "propStr1");
            return (Criteria) this;
        }

        public Criteria andPropStr1NotLike(String value) {
            addCriterion("prop_str1 not like", value, "propStr1");
            return (Criteria) this;
        }

        public Criteria andPropStr1In(List<String> values) {
            addCriterion("prop_str1 in", values, "propStr1");
            return (Criteria) this;
        }

        public Criteria andPropStr1NotIn(List<String> values) {
            addCriterion("prop_str1 not in", values, "propStr1");
            return (Criteria) this;
        }

        public Criteria andPropStr1Between(String value1, String value2) {
            addCriterion("prop_str1 between", value1, value2, "propStr1");
            return (Criteria) this;
        }

        public Criteria andPropStr1NotBetween(String value1, String value2) {
            addCriterion("prop_str1 not between", value1, value2, "propStr1");
            return (Criteria) this;
        }

        public Criteria andPropStr2IsNull() {
            addCriterion("prop_str2 is null");
            return (Criteria) this;
        }

        public Criteria andPropStr2IsNotNull() {
            addCriterion("prop_str2 is not null");
            return (Criteria) this;
        }

        public Criteria andPropStr2EqualTo(String value) {
            addCriterion("prop_str2 =", value, "propStr2");
            return (Criteria) this;
        }

        public Criteria andPropStr2NotEqualTo(String value) {
            addCriterion("prop_str2 <>", value, "propStr2");
            return (Criteria) this;
        }

        public Criteria andPropStr2GreaterThan(String value) {
            addCriterion("prop_str2 >", value, "propStr2");
            return (Criteria) this;
        }

        public Criteria andPropStr2GreaterThanOrEqualTo(String value) {
            addCriterion("prop_str2 >=", value, "propStr2");
            return (Criteria) this;
        }

        public Criteria andPropStr2LessThan(String value) {
            addCriterion("prop_str2 <", value, "propStr2");
            return (Criteria) this;
        }

        public Criteria andPropStr2LessThanOrEqualTo(String value) {
            addCriterion("prop_str2 <=", value, "propStr2");
            return (Criteria) this;
        }

        public Criteria andPropStr2Like(String value) {
            addCriterion("prop_str2 like", value, "propStr2");
            return (Criteria) this;
        }

        public Criteria andPropStr2NotLike(String value) {
            addCriterion("prop_str2 not like", value, "propStr2");
            return (Criteria) this;
        }

        public Criteria andPropStr2In(List<String> values) {
            addCriterion("prop_str2 in", values, "propStr2");
            return (Criteria) this;
        }

        public Criteria andPropStr2NotIn(List<String> values) {
            addCriterion("prop_str2 not in", values, "propStr2");
            return (Criteria) this;
        }

        public Criteria andPropStr2Between(String value1, String value2) {
            addCriterion("prop_str2 between", value1, value2, "propStr2");
            return (Criteria) this;
        }

        public Criteria andPropStr2NotBetween(String value1, String value2) {
            addCriterion("prop_str2 not between", value1, value2, "propStr2");
            return (Criteria) this;
        }

        public Criteria andPropStr3IsNull() {
            addCriterion("prop_str3 is null");
            return (Criteria) this;
        }

        public Criteria andPropStr3IsNotNull() {
            addCriterion("prop_str3 is not null");
            return (Criteria) this;
        }

        public Criteria andPropStr3EqualTo(String value) {
            addCriterion("prop_str3 =", value, "propStr3");
            return (Criteria) this;
        }

        public Criteria andPropStr3NotEqualTo(String value) {
            addCriterion("prop_str3 <>", value, "propStr3");
            return (Criteria) this;
        }

        public Criteria andPropStr3GreaterThan(String value) {
            addCriterion("prop_str3 >", value, "propStr3");
            return (Criteria) this;
        }

        public Criteria andPropStr3GreaterThanOrEqualTo(String value) {
            addCriterion("prop_str3 >=", value, "propStr3");
            return (Criteria) this;
        }

        public Criteria andPropStr3LessThan(String value) {
            addCriterion("prop_str3 <", value, "propStr3");
            return (Criteria) this;
        }

        public Criteria andPropStr3LessThanOrEqualTo(String value) {
            addCriterion("prop_str3 <=", value, "propStr3");
            return (Criteria) this;
        }

        public Criteria andPropStr3Like(String value) {
            addCriterion("prop_str3 like", value, "propStr3");
            return (Criteria) this;
        }

        public Criteria andPropStr3NotLike(String value) {
            addCriterion("prop_str3 not like", value, "propStr3");
            return (Criteria) this;
        }

        public Criteria andPropStr3In(List<String> values) {
            addCriterion("prop_str3 in", values, "propStr3");
            return (Criteria) this;
        }

        public Criteria andPropStr3NotIn(List<String> values) {
            addCriterion("prop_str3 not in", values, "propStr3");
            return (Criteria) this;
        }

        public Criteria andPropStr3Between(String value1, String value2) {
            addCriterion("prop_str3 between", value1, value2, "propStr3");
            return (Criteria) this;
        }

        public Criteria andPropStr3NotBetween(String value1, String value2) {
            addCriterion("prop_str3 not between", value1, value2, "propStr3");
            return (Criteria) this;
        }

        public Criteria andPropInt1IsNull() {
            addCriterion("prop_int1 is null");
            return (Criteria) this;
        }

        public Criteria andPropInt1IsNotNull() {
            addCriterion("prop_int1 is not null");
            return (Criteria) this;
        }

        public Criteria andPropInt1EqualTo(Integer value) {
            addCriterion("prop_int1 =", value, "propInt1");
            return (Criteria) this;
        }

        public Criteria andPropInt1NotEqualTo(Integer value) {
            addCriterion("prop_int1 <>", value, "propInt1");
            return (Criteria) this;
        }

        public Criteria andPropInt1GreaterThan(Integer value) {
            addCriterion("prop_int1 >", value, "propInt1");
            return (Criteria) this;
        }

        public Criteria andPropInt1GreaterThanOrEqualTo(Integer value) {
            addCriterion("prop_int1 >=", value, "propInt1");
            return (Criteria) this;
        }

        public Criteria andPropInt1LessThan(Integer value) {
            addCriterion("prop_int1 <", value, "propInt1");
            return (Criteria) this;
        }

        public Criteria andPropInt1LessThanOrEqualTo(Integer value) {
            addCriterion("prop_int1 <=", value, "propInt1");
            return (Criteria) this;
        }

        public Criteria andPropInt1In(List<Integer> values) {
            addCriterion("prop_int1 in", values, "propInt1");
            return (Criteria) this;
        }

        public Criteria andPropInt1NotIn(List<Integer> values) {
            addCriterion("prop_int1 not in", values, "propInt1");
            return (Criteria) this;
        }

        public Criteria andPropInt1Between(Integer value1, Integer value2) {
            addCriterion("prop_int1 between", value1, value2, "propInt1");
            return (Criteria) this;
        }

        public Criteria andPropInt1NotBetween(Integer value1, Integer value2) {
            addCriterion("prop_int1 not between", value1, value2, "propInt1");
            return (Criteria) this;
        }

        public Criteria andPropInt2IsNull() {
            addCriterion("prop_int2 is null");
            return (Criteria) this;
        }

        public Criteria andPropInt2IsNotNull() {
            addCriterion("prop_int2 is not null");
            return (Criteria) this;
        }

        public Criteria andPropInt2EqualTo(Integer value) {
            addCriterion("prop_int2 =", value, "propInt2");
            return (Criteria) this;
        }

        public Criteria andPropInt2NotEqualTo(Integer value) {
            addCriterion("prop_int2 <>", value, "propInt2");
            return (Criteria) this;
        }

        public Criteria andPropInt2GreaterThan(Integer value) {
            addCriterion("prop_int2 >", value, "propInt2");
            return (Criteria) this;
        }

        public Criteria andPropInt2GreaterThanOrEqualTo(Integer value) {
            addCriterion("prop_int2 >=", value, "propInt2");
            return (Criteria) this;
        }

        public Criteria andPropInt2LessThan(Integer value) {
            addCriterion("prop_int2 <", value, "propInt2");
            return (Criteria) this;
        }

        public Criteria andPropInt2LessThanOrEqualTo(Integer value) {
            addCriterion("prop_int2 <=", value, "propInt2");
            return (Criteria) this;
        }

        public Criteria andPropInt2In(List<Integer> values) {
            addCriterion("prop_int2 in", values, "propInt2");
            return (Criteria) this;
        }

        public Criteria andPropInt2NotIn(List<Integer> values) {
            addCriterion("prop_int2 not in", values, "propInt2");
            return (Criteria) this;
        }

        public Criteria andPropInt2Between(Integer value1, Integer value2) {
            addCriterion("prop_int2 between", value1, value2, "propInt2");
            return (Criteria) this;
        }

        public Criteria andPropInt2NotBetween(Integer value1, Integer value2) {
            addCriterion("prop_int2 not between", value1, value2, "propInt2");
            return (Criteria) this;
        }

        public Criteria andPropInt3IsNull() {
            addCriterion("prop_int3 is null");
            return (Criteria) this;
        }

        public Criteria andPropInt3IsNotNull() {
            addCriterion("prop_int3 is not null");
            return (Criteria) this;
        }

        public Criteria andPropInt3EqualTo(Integer value) {
            addCriterion("prop_int3 =", value, "propInt3");
            return (Criteria) this;
        }

        public Criteria andPropInt3NotEqualTo(Integer value) {
            addCriterion("prop_int3 <>", value, "propInt3");
            return (Criteria) this;
        }

        public Criteria andPropInt3GreaterThan(Integer value) {
            addCriterion("prop_int3 >", value, "propInt3");
            return (Criteria) this;
        }

        public Criteria andPropInt3GreaterThanOrEqualTo(Integer value) {
            addCriterion("prop_int3 >=", value, "propInt3");
            return (Criteria) this;
        }

        public Criteria andPropInt3LessThan(Integer value) {
            addCriterion("prop_int3 <", value, "propInt3");
            return (Criteria) this;
        }

        public Criteria andPropInt3LessThanOrEqualTo(Integer value) {
            addCriterion("prop_int3 <=", value, "propInt3");
            return (Criteria) this;
        }

        public Criteria andPropInt3In(List<Integer> values) {
            addCriterion("prop_int3 in", values, "propInt3");
            return (Criteria) this;
        }

        public Criteria andPropInt3NotIn(List<Integer> values) {
            addCriterion("prop_int3 not in", values, "propInt3");
            return (Criteria) this;
        }

        public Criteria andPropInt3Between(Integer value1, Integer value2) {
            addCriterion("prop_int3 between", value1, value2, "propInt3");
            return (Criteria) this;
        }

        public Criteria andPropInt3NotBetween(Integer value1, Integer value2) {
            addCriterion("prop_int3 not between", value1, value2, "propInt3");
            return (Criteria) this;
        }

        public Criteria andPropFloat1IsNull() {
            addCriterion("prop_float1 is null");
            return (Criteria) this;
        }

        public Criteria andPropFloat1IsNotNull() {
            addCriterion("prop_float1 is not null");
            return (Criteria) this;
        }

        public Criteria andPropFloat1EqualTo(Float value) {
            addCriterion("prop_float1 =", value, "propFloat1");
            return (Criteria) this;
        }

        public Criteria andPropFloat1NotEqualTo(Float value) {
            addCriterion("prop_float1 <>", value, "propFloat1");
            return (Criteria) this;
        }

        public Criteria andPropFloat1GreaterThan(Float value) {
            addCriterion("prop_float1 >", value, "propFloat1");
            return (Criteria) this;
        }

        public Criteria andPropFloat1GreaterThanOrEqualTo(Float value) {
            addCriterion("prop_float1 >=", value, "propFloat1");
            return (Criteria) this;
        }

        public Criteria andPropFloat1LessThan(Float value) {
            addCriterion("prop_float1 <", value, "propFloat1");
            return (Criteria) this;
        }

        public Criteria andPropFloat1LessThanOrEqualTo(Float value) {
            addCriterion("prop_float1 <=", value, "propFloat1");
            return (Criteria) this;
        }

        public Criteria andPropFloat1In(List<Float> values) {
            addCriterion("prop_float1 in", values, "propFloat1");
            return (Criteria) this;
        }

        public Criteria andPropFloat1NotIn(List<Float> values) {
            addCriterion("prop_float1 not in", values, "propFloat1");
            return (Criteria) this;
        }

        public Criteria andPropFloat1Between(Float value1, Float value2) {
            addCriterion("prop_float1 between", value1, value2, "propFloat1");
            return (Criteria) this;
        }

        public Criteria andPropFloat1NotBetween(Float value1, Float value2) {
            addCriterion("prop_float1 not between", value1, value2, "propFloat1");
            return (Criteria) this;
        }

        public Criteria andPropFloat2IsNull() {
            addCriterion("prop_float2 is null");
            return (Criteria) this;
        }

        public Criteria andPropFloat2IsNotNull() {
            addCriterion("prop_float2 is not null");
            return (Criteria) this;
        }

        public Criteria andPropFloat2EqualTo(Float value) {
            addCriterion("prop_float2 =", value, "propFloat2");
            return (Criteria) this;
        }

        public Criteria andPropFloat2NotEqualTo(Float value) {
            addCriterion("prop_float2 <>", value, "propFloat2");
            return (Criteria) this;
        }

        public Criteria andPropFloat2GreaterThan(Float value) {
            addCriterion("prop_float2 >", value, "propFloat2");
            return (Criteria) this;
        }

        public Criteria andPropFloat2GreaterThanOrEqualTo(Float value) {
            addCriterion("prop_float2 >=", value, "propFloat2");
            return (Criteria) this;
        }

        public Criteria andPropFloat2LessThan(Float value) {
            addCriterion("prop_float2 <", value, "propFloat2");
            return (Criteria) this;
        }

        public Criteria andPropFloat2LessThanOrEqualTo(Float value) {
            addCriterion("prop_float2 <=", value, "propFloat2");
            return (Criteria) this;
        }

        public Criteria andPropFloat2In(List<Float> values) {
            addCriterion("prop_float2 in", values, "propFloat2");
            return (Criteria) this;
        }

        public Criteria andPropFloat2NotIn(List<Float> values) {
            addCriterion("prop_float2 not in", values, "propFloat2");
            return (Criteria) this;
        }

        public Criteria andPropFloat2Between(Float value1, Float value2) {
            addCriterion("prop_float2 between", value1, value2, "propFloat2");
            return (Criteria) this;
        }

        public Criteria andPropFloat2NotBetween(Float value1, Float value2) {
            addCriterion("prop_float2 not between", value1, value2, "propFloat2");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andImpUnitTypeIsNull() {
            addCriterion("imp_unit_type is null");
            return (Criteria) this;
        }

        public Criteria andImpUnitTypeIsNotNull() {
            addCriterion("imp_unit_type is not null");
            return (Criteria) this;
        }

        public Criteria andImpUnitTypeEqualTo(String value) {
            addCriterion("imp_unit_type =", value, "impUnitType");
            return (Criteria) this;
        }

        public Criteria andImpUnitTypeNotEqualTo(String value) {
            addCriterion("imp_unit_type <>", value, "impUnitType");
            return (Criteria) this;
        }

        public Criteria andImpUnitTypeGreaterThan(String value) {
            addCriterion("imp_unit_type >", value, "impUnitType");
            return (Criteria) this;
        }

        public Criteria andImpUnitTypeGreaterThanOrEqualTo(String value) {
            addCriterion("imp_unit_type >=", value, "impUnitType");
            return (Criteria) this;
        }

        public Criteria andImpUnitTypeLessThan(String value) {
            addCriterion("imp_unit_type <", value, "impUnitType");
            return (Criteria) this;
        }

        public Criteria andImpUnitTypeLessThanOrEqualTo(String value) {
            addCriterion("imp_unit_type <=", value, "impUnitType");
            return (Criteria) this;
        }

        public Criteria andImpUnitTypeLike(String value) {
            addCriterion("imp_unit_type like", value, "impUnitType");
            return (Criteria) this;
        }

        public Criteria andImpUnitTypeNotLike(String value) {
            addCriterion("imp_unit_type not like", value, "impUnitType");
            return (Criteria) this;
        }

        public Criteria andImpUnitTypeIn(List<String> values) {
            addCriterion("imp_unit_type in", values, "impUnitType");
            return (Criteria) this;
        }

        public Criteria andImpUnitTypeNotIn(List<String> values) {
            addCriterion("imp_unit_type not in", values, "impUnitType");
            return (Criteria) this;
        }

        public Criteria andImpUnitTypeBetween(String value1, String value2) {
            addCriterion("imp_unit_type between", value1, value2, "impUnitType");
            return (Criteria) this;
        }

        public Criteria andImpUnitTypeNotBetween(String value1, String value2) {
            addCriterion("imp_unit_type not between", value1, value2, "impUnitType");
            return (Criteria) this;
        }

        public Criteria andImpUnitIdIsNull() {
            addCriterion("imp_unit_id is null");
            return (Criteria) this;
        }

        public Criteria andImpUnitIdIsNotNull() {
            addCriterion("imp_unit_id is not null");
            return (Criteria) this;
        }

        public Criteria andImpUnitIdEqualTo(Integer value) {
            addCriterion("imp_unit_id =", value, "impUnitId");
            return (Criteria) this;
        }

        public Criteria andImpUnitIdNotEqualTo(Integer value) {
            addCriterion("imp_unit_id <>", value, "impUnitId");
            return (Criteria) this;
        }

        public Criteria andImpUnitIdGreaterThan(Integer value) {
            addCriterion("imp_unit_id >", value, "impUnitId");
            return (Criteria) this;
        }

        public Criteria andImpUnitIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("imp_unit_id >=", value, "impUnitId");
            return (Criteria) this;
        }

        public Criteria andImpUnitIdLessThan(Integer value) {
            addCriterion("imp_unit_id <", value, "impUnitId");
            return (Criteria) this;
        }

        public Criteria andImpUnitIdLessThanOrEqualTo(Integer value) {
            addCriterion("imp_unit_id <=", value, "impUnitId");
            return (Criteria) this;
        }

        public Criteria andImpUnitIdIn(List<Integer> values) {
            addCriterion("imp_unit_id in", values, "impUnitId");
            return (Criteria) this;
        }

        public Criteria andImpUnitIdNotIn(List<Integer> values) {
            addCriterion("imp_unit_id not in", values, "impUnitId");
            return (Criteria) this;
        }

        public Criteria andImpUnitIdBetween(Integer value1, Integer value2) {
            addCriterion("imp_unit_id between", value1, value2, "impUnitId");
            return (Criteria) this;
        }

        public Criteria andImpUnitIdNotBetween(Integer value1, Integer value2) {
            addCriterion("imp_unit_id not between", value1, value2, "impUnitId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table spider_resc_info
     *
     * @mbggenerated do_not_delete_during_merge Fri Feb 17 11:22:45 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table spider_resc_info
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}