package com.xxx.collect.base.model;

import java.io.Serializable;
import java.util.Date;

public class SpiderRescInfo extends SpiderRescInfoKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.name
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.pic
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.pic_file_id
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private Integer picFileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.content
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.tags1
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private String tags1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.tags2
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private String tags2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.tags3
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private String tags3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.tags4
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private String tags4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.cat
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private String cat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.sub_cat
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private String subCat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.sub_cat_lv3
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private String subCatLv3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.sub_cat_lv4
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private String subCatLv4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.buy_cnt
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private Integer buyCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.good_cnt
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private Integer goodCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.fav_cnt
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private Integer favCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.coin
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private Double coin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.user
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private String user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.resc_create_time
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private Date rescCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.down_file_path
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private String downFilePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.file_id
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.prop_str1
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private String propStr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.prop_str2
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private String propStr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.prop_str3
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private String propStr3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.prop_int1
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private Integer propInt1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.prop_int2
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private Integer propInt2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.prop_int3
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private Integer propInt3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.prop_float1
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private Float propFloat1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.prop_float2
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private Float propFloat2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.create_time
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.imp_unit_type
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private String impUnitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.imp_unit_id
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private Integer impUnitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_resc_info.content2
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private String content2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spider_resc_info
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.name
     *
     * @return the value of spider_resc_info.name
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.name
     *
     * @param name the value for spider_resc_info.name
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.pic
     *
     * @return the value of spider_resc_info.pic
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.pic
     *
     * @param pic the value for spider_resc_info.pic
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.pic_file_id
     *
     * @return the value of spider_resc_info.pic_file_id
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public Integer getPicFileId() {
        return picFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.pic_file_id
     *
     * @param picFileId the value for spider_resc_info.pic_file_id
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setPicFileId(Integer picFileId) {
        this.picFileId = picFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.content
     *
     * @return the value of spider_resc_info.content
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.content
     *
     * @param content the value for spider_resc_info.content
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.tags1
     *
     * @return the value of spider_resc_info.tags1
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public String getTags1() {
        return tags1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.tags1
     *
     * @param tags1 the value for spider_resc_info.tags1
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setTags1(String tags1) {
        this.tags1 = tags1 == null ? null : tags1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.tags2
     *
     * @return the value of spider_resc_info.tags2
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public String getTags2() {
        return tags2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.tags2
     *
     * @param tags2 the value for spider_resc_info.tags2
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setTags2(String tags2) {
        this.tags2 = tags2 == null ? null : tags2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.tags3
     *
     * @return the value of spider_resc_info.tags3
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public String getTags3() {
        return tags3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.tags3
     *
     * @param tags3 the value for spider_resc_info.tags3
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setTags3(String tags3) {
        this.tags3 = tags3 == null ? null : tags3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.tags4
     *
     * @return the value of spider_resc_info.tags4
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public String getTags4() {
        return tags4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.tags4
     *
     * @param tags4 the value for spider_resc_info.tags4
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setTags4(String tags4) {
        this.tags4 = tags4 == null ? null : tags4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.cat
     *
     * @return the value of spider_resc_info.cat
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public String getCat() {
        return cat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.cat
     *
     * @param cat the value for spider_resc_info.cat
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setCat(String cat) {
        this.cat = cat == null ? null : cat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.sub_cat
     *
     * @return the value of spider_resc_info.sub_cat
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public String getSubCat() {
        return subCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.sub_cat
     *
     * @param subCat the value for spider_resc_info.sub_cat
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setSubCat(String subCat) {
        this.subCat = subCat == null ? null : subCat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.sub_cat_lv3
     *
     * @return the value of spider_resc_info.sub_cat_lv3
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public String getSubCatLv3() {
        return subCatLv3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.sub_cat_lv3
     *
     * @param subCatLv3 the value for spider_resc_info.sub_cat_lv3
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setSubCatLv3(String subCatLv3) {
        this.subCatLv3 = subCatLv3 == null ? null : subCatLv3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.sub_cat_lv4
     *
     * @return the value of spider_resc_info.sub_cat_lv4
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public String getSubCatLv4() {
        return subCatLv4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.sub_cat_lv4
     *
     * @param subCatLv4 the value for spider_resc_info.sub_cat_lv4
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setSubCatLv4(String subCatLv4) {
        this.subCatLv4 = subCatLv4 == null ? null : subCatLv4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.buy_cnt
     *
     * @return the value of spider_resc_info.buy_cnt
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public Integer getBuyCnt() {
        return buyCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.buy_cnt
     *
     * @param buyCnt the value for spider_resc_info.buy_cnt
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setBuyCnt(Integer buyCnt) {
        this.buyCnt = buyCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.good_cnt
     *
     * @return the value of spider_resc_info.good_cnt
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public Integer getGoodCnt() {
        return goodCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.good_cnt
     *
     * @param goodCnt the value for spider_resc_info.good_cnt
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setGoodCnt(Integer goodCnt) {
        this.goodCnt = goodCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.fav_cnt
     *
     * @return the value of spider_resc_info.fav_cnt
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public Integer getFavCnt() {
        return favCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.fav_cnt
     *
     * @param favCnt the value for spider_resc_info.fav_cnt
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setFavCnt(Integer favCnt) {
        this.favCnt = favCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.coin
     *
     * @return the value of spider_resc_info.coin
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public Double getCoin() {
        return coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.coin
     *
     * @param coin the value for spider_resc_info.coin
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setCoin(Double coin) {
        this.coin = coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.user
     *
     * @return the value of spider_resc_info.user
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.user
     *
     * @param user the value for spider_resc_info.user
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.resc_create_time
     *
     * @return the value of spider_resc_info.resc_create_time
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public Date getRescCreateTime() {
        return rescCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.resc_create_time
     *
     * @param rescCreateTime the value for spider_resc_info.resc_create_time
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setRescCreateTime(Date rescCreateTime) {
        this.rescCreateTime = rescCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.down_file_path
     *
     * @return the value of spider_resc_info.down_file_path
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public String getDownFilePath() {
        return downFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.down_file_path
     *
     * @param downFilePath the value for spider_resc_info.down_file_path
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setDownFilePath(String downFilePath) {
        this.downFilePath = downFilePath == null ? null : downFilePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.file_id
     *
     * @return the value of spider_resc_info.file_id
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.file_id
     *
     * @param fileId the value for spider_resc_info.file_id
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.prop_str1
     *
     * @return the value of spider_resc_info.prop_str1
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public String getPropStr1() {
        return propStr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.prop_str1
     *
     * @param propStr1 the value for spider_resc_info.prop_str1
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setPropStr1(String propStr1) {
        this.propStr1 = propStr1 == null ? null : propStr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.prop_str2
     *
     * @return the value of spider_resc_info.prop_str2
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public String getPropStr2() {
        return propStr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.prop_str2
     *
     * @param propStr2 the value for spider_resc_info.prop_str2
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setPropStr2(String propStr2) {
        this.propStr2 = propStr2 == null ? null : propStr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.prop_str3
     *
     * @return the value of spider_resc_info.prop_str3
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public String getPropStr3() {
        return propStr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.prop_str3
     *
     * @param propStr3 the value for spider_resc_info.prop_str3
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setPropStr3(String propStr3) {
        this.propStr3 = propStr3 == null ? null : propStr3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.prop_int1
     *
     * @return the value of spider_resc_info.prop_int1
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public Integer getPropInt1() {
        return propInt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.prop_int1
     *
     * @param propInt1 the value for spider_resc_info.prop_int1
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setPropInt1(Integer propInt1) {
        this.propInt1 = propInt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.prop_int2
     *
     * @return the value of spider_resc_info.prop_int2
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public Integer getPropInt2() {
        return propInt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.prop_int2
     *
     * @param propInt2 the value for spider_resc_info.prop_int2
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setPropInt2(Integer propInt2) {
        this.propInt2 = propInt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.prop_int3
     *
     * @return the value of spider_resc_info.prop_int3
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public Integer getPropInt3() {
        return propInt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.prop_int3
     *
     * @param propInt3 the value for spider_resc_info.prop_int3
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setPropInt3(Integer propInt3) {
        this.propInt3 = propInt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.prop_float1
     *
     * @return the value of spider_resc_info.prop_float1
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public Float getPropFloat1() {
        return propFloat1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.prop_float1
     *
     * @param propFloat1 the value for spider_resc_info.prop_float1
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setPropFloat1(Float propFloat1) {
        this.propFloat1 = propFloat1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.prop_float2
     *
     * @return the value of spider_resc_info.prop_float2
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public Float getPropFloat2() {
        return propFloat2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.prop_float2
     *
     * @param propFloat2 the value for spider_resc_info.prop_float2
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setPropFloat2(Float propFloat2) {
        this.propFloat2 = propFloat2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.create_time
     *
     * @return the value of spider_resc_info.create_time
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.create_time
     *
     * @param createTime the value for spider_resc_info.create_time
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.imp_unit_type
     *
     * @return the value of spider_resc_info.imp_unit_type
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public String getImpUnitType() {
        return impUnitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.imp_unit_type
     *
     * @param impUnitType the value for spider_resc_info.imp_unit_type
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setImpUnitType(String impUnitType) {
        this.impUnitType = impUnitType == null ? null : impUnitType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.imp_unit_id
     *
     * @return the value of spider_resc_info.imp_unit_id
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public Integer getImpUnitId() {
        return impUnitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.imp_unit_id
     *
     * @param impUnitId the value for spider_resc_info.imp_unit_id
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setImpUnitId(Integer impUnitId) {
        this.impUnitId = impUnitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_resc_info.content2
     *
     * @return the value of spider_resc_info.content2
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public String getContent2() {
        return content2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_resc_info.content2
     *
     * @param content2 the value for spider_resc_info.content2
     *
     * @mbggenerated Fri Feb 17 11:22:45 CST 2017
     */
    public void setContent2(String content2) {
        this.content2 = content2 == null ? null : content2.trim();
    }
}