package com.xxx.collect.base.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TaskInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public TaskInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTaskNameIsNull() {
            addCriterion("TASK_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTaskNameIsNotNull() {
            addCriterion("TASK_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTaskNameEqualTo(String value) {
            addCriterion("TASK_NAME =", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotEqualTo(String value) {
            addCriterion("TASK_NAME <>", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameGreaterThan(String value) {
            addCriterion("TASK_NAME >", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameGreaterThanOrEqualTo(String value) {
            addCriterion("TASK_NAME >=", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameLessThan(String value) {
            addCriterion("TASK_NAME <", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameLessThanOrEqualTo(String value) {
            addCriterion("TASK_NAME <=", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameLike(String value) {
            addCriterion("TASK_NAME like", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotLike(String value) {
            addCriterion("TASK_NAME not like", value, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameIn(List<String> values) {
            addCriterion("TASK_NAME in", values, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotIn(List<String> values) {
            addCriterion("TASK_NAME not in", values, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameBetween(String value1, String value2) {
            addCriterion("TASK_NAME between", value1, value2, "taskName");
            return (Criteria) this;
        }

        public Criteria andTaskNameNotBetween(String value1, String value2) {
            addCriterion("TASK_NAME not between", value1, value2, "taskName");
            return (Criteria) this;
        }

        public Criteria andInfoIdIsNull() {
            addCriterion("INFO_ID is null");
            return (Criteria) this;
        }

        public Criteria andInfoIdIsNotNull() {
            addCriterion("INFO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInfoIdEqualTo(String value) {
            addCriterion("INFO_ID =", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotEqualTo(String value) {
            addCriterion("INFO_ID <>", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdGreaterThan(String value) {
            addCriterion("INFO_ID >", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdGreaterThanOrEqualTo(String value) {
            addCriterion("INFO_ID >=", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdLessThan(String value) {
            addCriterion("INFO_ID <", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdLessThanOrEqualTo(String value) {
            addCriterion("INFO_ID <=", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdLike(String value) {
            addCriterion("INFO_ID like", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotLike(String value) {
            addCriterion("INFO_ID not like", value, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdIn(List<String> values) {
            addCriterion("INFO_ID in", values, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotIn(List<String> values) {
            addCriterion("INFO_ID not in", values, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdBetween(String value1, String value2) {
            addCriterion("INFO_ID between", value1, value2, "infoId");
            return (Criteria) this;
        }

        public Criteria andInfoIdNotBetween(String value1, String value2) {
            addCriterion("INFO_ID not between", value1, value2, "infoId");
            return (Criteria) this;
        }

        public Criteria andBanchIsNull() {
            addCriterion("BANCH is null");
            return (Criteria) this;
        }

        public Criteria andBanchIsNotNull() {
            addCriterion("BANCH is not null");
            return (Criteria) this;
        }

        public Criteria andBanchEqualTo(Long value) {
            addCriterion("BANCH =", value, "banch");
            return (Criteria) this;
        }

        public Criteria andBanchNotEqualTo(Long value) {
            addCriterion("BANCH <>", value, "banch");
            return (Criteria) this;
        }

        public Criteria andBanchGreaterThan(Long value) {
            addCriterion("BANCH >", value, "banch");
            return (Criteria) this;
        }

        public Criteria andBanchGreaterThanOrEqualTo(Long value) {
            addCriterion("BANCH >=", value, "banch");
            return (Criteria) this;
        }

        public Criteria andBanchLessThan(Long value) {
            addCriterion("BANCH <", value, "banch");
            return (Criteria) this;
        }

        public Criteria andBanchLessThanOrEqualTo(Long value) {
            addCriterion("BANCH <=", value, "banch");
            return (Criteria) this;
        }

        public Criteria andBanchIn(List<Long> values) {
            addCriterion("BANCH in", values, "banch");
            return (Criteria) this;
        }

        public Criteria andBanchNotIn(List<Long> values) {
            addCriterion("BANCH not in", values, "banch");
            return (Criteria) this;
        }

        public Criteria andBanchBetween(Long value1, Long value2) {
            addCriterion("BANCH between", value1, value2, "banch");
            return (Criteria) this;
        }

        public Criteria andBanchNotBetween(Long value1, Long value2) {
            addCriterion("BANCH not between", value1, value2, "banch");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("START_DATE is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("START_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(String value) {
            addCriterion("START_DATE =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(String value) {
            addCriterion("START_DATE <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(String value) {
            addCriterion("START_DATE >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(String value) {
            addCriterion("START_DATE >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(String value) {
            addCriterion("START_DATE <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(String value) {
            addCriterion("START_DATE <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLike(String value) {
            addCriterion("START_DATE like", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotLike(String value) {
            addCriterion("START_DATE not like", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<String> values) {
            addCriterion("START_DATE in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<String> values) {
            addCriterion("START_DATE not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(String value1, String value2) {
            addCriterion("START_DATE between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(String value1, String value2) {
            addCriterion("START_DATE not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("END_DATE is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("END_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(String value) {
            addCriterion("END_DATE =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(String value) {
            addCriterion("END_DATE <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(String value) {
            addCriterion("END_DATE >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(String value) {
            addCriterion("END_DATE >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(String value) {
            addCriterion("END_DATE <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(String value) {
            addCriterion("END_DATE <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLike(String value) {
            addCriterion("END_DATE like", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotLike(String value) {
            addCriterion("END_DATE not like", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<String> values) {
            addCriterion("END_DATE in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<String> values) {
            addCriterion("END_DATE not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(String value1, String value2) {
            addCriterion("END_DATE between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(String value1, String value2) {
            addCriterion("END_DATE not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andSuccNumIsNull() {
            addCriterion("SUCC_NUM is null");
            return (Criteria) this;
        }

        public Criteria andSuccNumIsNotNull() {
            addCriterion("SUCC_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andSuccNumEqualTo(Long value) {
            addCriterion("SUCC_NUM =", value, "succNum");
            return (Criteria) this;
        }

        public Criteria andSuccNumNotEqualTo(Long value) {
            addCriterion("SUCC_NUM <>", value, "succNum");
            return (Criteria) this;
        }

        public Criteria andSuccNumGreaterThan(Long value) {
            addCriterion("SUCC_NUM >", value, "succNum");
            return (Criteria) this;
        }

        public Criteria andSuccNumGreaterThanOrEqualTo(Long value) {
            addCriterion("SUCC_NUM >=", value, "succNum");
            return (Criteria) this;
        }

        public Criteria andSuccNumLessThan(Long value) {
            addCriterion("SUCC_NUM <", value, "succNum");
            return (Criteria) this;
        }

        public Criteria andSuccNumLessThanOrEqualTo(Long value) {
            addCriterion("SUCC_NUM <=", value, "succNum");
            return (Criteria) this;
        }

        public Criteria andSuccNumIn(List<Long> values) {
            addCriterion("SUCC_NUM in", values, "succNum");
            return (Criteria) this;
        }

        public Criteria andSuccNumNotIn(List<Long> values) {
            addCriterion("SUCC_NUM not in", values, "succNum");
            return (Criteria) this;
        }

        public Criteria andSuccNumBetween(Long value1, Long value2) {
            addCriterion("SUCC_NUM between", value1, value2, "succNum");
            return (Criteria) this;
        }

        public Criteria andSuccNumNotBetween(Long value1, Long value2) {
            addCriterion("SUCC_NUM not between", value1, value2, "succNum");
            return (Criteria) this;
        }

        public Criteria andErroNumIsNull() {
            addCriterion("ERRO_NUM is null");
            return (Criteria) this;
        }

        public Criteria andErroNumIsNotNull() {
            addCriterion("ERRO_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andErroNumEqualTo(Long value) {
            addCriterion("ERRO_NUM =", value, "erroNum");
            return (Criteria) this;
        }

        public Criteria andErroNumNotEqualTo(Long value) {
            addCriterion("ERRO_NUM <>", value, "erroNum");
            return (Criteria) this;
        }

        public Criteria andErroNumGreaterThan(Long value) {
            addCriterion("ERRO_NUM >", value, "erroNum");
            return (Criteria) this;
        }

        public Criteria andErroNumGreaterThanOrEqualTo(Long value) {
            addCriterion("ERRO_NUM >=", value, "erroNum");
            return (Criteria) this;
        }

        public Criteria andErroNumLessThan(Long value) {
            addCriterion("ERRO_NUM <", value, "erroNum");
            return (Criteria) this;
        }

        public Criteria andErroNumLessThanOrEqualTo(Long value) {
            addCriterion("ERRO_NUM <=", value, "erroNum");
            return (Criteria) this;
        }

        public Criteria andErroNumIn(List<Long> values) {
            addCriterion("ERRO_NUM in", values, "erroNum");
            return (Criteria) this;
        }

        public Criteria andErroNumNotIn(List<Long> values) {
            addCriterion("ERRO_NUM not in", values, "erroNum");
            return (Criteria) this;
        }

        public Criteria andErroNumBetween(Long value1, Long value2) {
            addCriterion("ERRO_NUM between", value1, value2, "erroNum");
            return (Criteria) this;
        }

        public Criteria andErroNumNotBetween(Long value1, Long value2) {
            addCriterion("ERRO_NUM not between", value1, value2, "erroNum");
            return (Criteria) this;
        }

        public Criteria andInfoAIsNull() {
            addCriterion("INFO_A is null");
            return (Criteria) this;
        }

        public Criteria andInfoAIsNotNull() {
            addCriterion("INFO_A is not null");
            return (Criteria) this;
        }

        public Criteria andInfoAEqualTo(String value) {
            addCriterion("INFO_A =", value, "infoA");
            return (Criteria) this;
        }

        public Criteria andInfoANotEqualTo(String value) {
            addCriterion("INFO_A <>", value, "infoA");
            return (Criteria) this;
        }

        public Criteria andInfoAGreaterThan(String value) {
            addCriterion("INFO_A >", value, "infoA");
            return (Criteria) this;
        }

        public Criteria andInfoAGreaterThanOrEqualTo(String value) {
            addCriterion("INFO_A >=", value, "infoA");
            return (Criteria) this;
        }

        public Criteria andInfoALessThan(String value) {
            addCriterion("INFO_A <", value, "infoA");
            return (Criteria) this;
        }

        public Criteria andInfoALessThanOrEqualTo(String value) {
            addCriterion("INFO_A <=", value, "infoA");
            return (Criteria) this;
        }

        public Criteria andInfoALike(String value) {
            addCriterion("INFO_A like", value, "infoA");
            return (Criteria) this;
        }

        public Criteria andInfoANotLike(String value) {
            addCriterion("INFO_A not like", value, "infoA");
            return (Criteria) this;
        }

        public Criteria andInfoAIn(List<String> values) {
            addCriterion("INFO_A in", values, "infoA");
            return (Criteria) this;
        }

        public Criteria andInfoANotIn(List<String> values) {
            addCriterion("INFO_A not in", values, "infoA");
            return (Criteria) this;
        }

        public Criteria andInfoABetween(String value1, String value2) {
            addCriterion("INFO_A between", value1, value2, "infoA");
            return (Criteria) this;
        }

        public Criteria andInfoANotBetween(String value1, String value2) {
            addCriterion("INFO_A not between", value1, value2, "infoA");
            return (Criteria) this;
        }

        public Criteria andInfoBIsNull() {
            addCriterion("INFO_B is null");
            return (Criteria) this;
        }

        public Criteria andInfoBIsNotNull() {
            addCriterion("INFO_B is not null");
            return (Criteria) this;
        }

        public Criteria andInfoBEqualTo(String value) {
            addCriterion("INFO_B =", value, "infoB");
            return (Criteria) this;
        }

        public Criteria andInfoBNotEqualTo(String value) {
            addCriterion("INFO_B <>", value, "infoB");
            return (Criteria) this;
        }

        public Criteria andInfoBGreaterThan(String value) {
            addCriterion("INFO_B >", value, "infoB");
            return (Criteria) this;
        }

        public Criteria andInfoBGreaterThanOrEqualTo(String value) {
            addCriterion("INFO_B >=", value, "infoB");
            return (Criteria) this;
        }

        public Criteria andInfoBLessThan(String value) {
            addCriterion("INFO_B <", value, "infoB");
            return (Criteria) this;
        }

        public Criteria andInfoBLessThanOrEqualTo(String value) {
            addCriterion("INFO_B <=", value, "infoB");
            return (Criteria) this;
        }

        public Criteria andInfoBLike(String value) {
            addCriterion("INFO_B like", value, "infoB");
            return (Criteria) this;
        }

        public Criteria andInfoBNotLike(String value) {
            addCriterion("INFO_B not like", value, "infoB");
            return (Criteria) this;
        }

        public Criteria andInfoBIn(List<String> values) {
            addCriterion("INFO_B in", values, "infoB");
            return (Criteria) this;
        }

        public Criteria andInfoBNotIn(List<String> values) {
            addCriterion("INFO_B not in", values, "infoB");
            return (Criteria) this;
        }

        public Criteria andInfoBBetween(String value1, String value2) {
            addCriterion("INFO_B between", value1, value2, "infoB");
            return (Criteria) this;
        }

        public Criteria andInfoBNotBetween(String value1, String value2) {
            addCriterion("INFO_B not between", value1, value2, "infoB");
            return (Criteria) this;
        }

        public Criteria andInfoCIsNull() {
            addCriterion("INFO_C is null");
            return (Criteria) this;
        }

        public Criteria andInfoCIsNotNull() {
            addCriterion("INFO_C is not null");
            return (Criteria) this;
        }

        public Criteria andInfoCEqualTo(String value) {
            addCriterion("INFO_C =", value, "infoC");
            return (Criteria) this;
        }

        public Criteria andInfoCNotEqualTo(String value) {
            addCriterion("INFO_C <>", value, "infoC");
            return (Criteria) this;
        }

        public Criteria andInfoCGreaterThan(String value) {
            addCriterion("INFO_C >", value, "infoC");
            return (Criteria) this;
        }

        public Criteria andInfoCGreaterThanOrEqualTo(String value) {
            addCriterion("INFO_C >=", value, "infoC");
            return (Criteria) this;
        }

        public Criteria andInfoCLessThan(String value) {
            addCriterion("INFO_C <", value, "infoC");
            return (Criteria) this;
        }

        public Criteria andInfoCLessThanOrEqualTo(String value) {
            addCriterion("INFO_C <=", value, "infoC");
            return (Criteria) this;
        }

        public Criteria andInfoCLike(String value) {
            addCriterion("INFO_C like", value, "infoC");
            return (Criteria) this;
        }

        public Criteria andInfoCNotLike(String value) {
            addCriterion("INFO_C not like", value, "infoC");
            return (Criteria) this;
        }

        public Criteria andInfoCIn(List<String> values) {
            addCriterion("INFO_C in", values, "infoC");
            return (Criteria) this;
        }

        public Criteria andInfoCNotIn(List<String> values) {
            addCriterion("INFO_C not in", values, "infoC");
            return (Criteria) this;
        }

        public Criteria andInfoCBetween(String value1, String value2) {
            addCriterion("INFO_C between", value1, value2, "infoC");
            return (Criteria) this;
        }

        public Criteria andInfoCNotBetween(String value1, String value2) {
            addCriterion("INFO_C not between", value1, value2, "infoC");
            return (Criteria) this;
        }

        public Criteria andInfoDIsNull() {
            addCriterion("INFO_D is null");
            return (Criteria) this;
        }

        public Criteria andInfoDIsNotNull() {
            addCriterion("INFO_D is not null");
            return (Criteria) this;
        }

        public Criteria andInfoDEqualTo(String value) {
            addCriterion("INFO_D =", value, "infoD");
            return (Criteria) this;
        }

        public Criteria andInfoDNotEqualTo(String value) {
            addCriterion("INFO_D <>", value, "infoD");
            return (Criteria) this;
        }

        public Criteria andInfoDGreaterThan(String value) {
            addCriterion("INFO_D >", value, "infoD");
            return (Criteria) this;
        }

        public Criteria andInfoDGreaterThanOrEqualTo(String value) {
            addCriterion("INFO_D >=", value, "infoD");
            return (Criteria) this;
        }

        public Criteria andInfoDLessThan(String value) {
            addCriterion("INFO_D <", value, "infoD");
            return (Criteria) this;
        }

        public Criteria andInfoDLessThanOrEqualTo(String value) {
            addCriterion("INFO_D <=", value, "infoD");
            return (Criteria) this;
        }

        public Criteria andInfoDLike(String value) {
            addCriterion("INFO_D like", value, "infoD");
            return (Criteria) this;
        }

        public Criteria andInfoDNotLike(String value) {
            addCriterion("INFO_D not like", value, "infoD");
            return (Criteria) this;
        }

        public Criteria andInfoDIn(List<String> values) {
            addCriterion("INFO_D in", values, "infoD");
            return (Criteria) this;
        }

        public Criteria andInfoDNotIn(List<String> values) {
            addCriterion("INFO_D not in", values, "infoD");
            return (Criteria) this;
        }

        public Criteria andInfoDBetween(String value1, String value2) {
            addCriterion("INFO_D between", value1, value2, "infoD");
            return (Criteria) this;
        }

        public Criteria andInfoDNotBetween(String value1, String value2) {
            addCriterion("INFO_D not between", value1, value2, "infoD");
            return (Criteria) this;
        }

        public Criteria andInfoEIsNull() {
            addCriterion("INFO_E is null");
            return (Criteria) this;
        }

        public Criteria andInfoEIsNotNull() {
            addCriterion("INFO_E is not null");
            return (Criteria) this;
        }

        public Criteria andInfoEEqualTo(String value) {
            addCriterion("INFO_E =", value, "infoE");
            return (Criteria) this;
        }

        public Criteria andInfoENotEqualTo(String value) {
            addCriterion("INFO_E <>", value, "infoE");
            return (Criteria) this;
        }

        public Criteria andInfoEGreaterThan(String value) {
            addCriterion("INFO_E >", value, "infoE");
            return (Criteria) this;
        }

        public Criteria andInfoEGreaterThanOrEqualTo(String value) {
            addCriterion("INFO_E >=", value, "infoE");
            return (Criteria) this;
        }

        public Criteria andInfoELessThan(String value) {
            addCriterion("INFO_E <", value, "infoE");
            return (Criteria) this;
        }

        public Criteria andInfoELessThanOrEqualTo(String value) {
            addCriterion("INFO_E <=", value, "infoE");
            return (Criteria) this;
        }

        public Criteria andInfoELike(String value) {
            addCriterion("INFO_E like", value, "infoE");
            return (Criteria) this;
        }

        public Criteria andInfoENotLike(String value) {
            addCriterion("INFO_E not like", value, "infoE");
            return (Criteria) this;
        }

        public Criteria andInfoEIn(List<String> values) {
            addCriterion("INFO_E in", values, "infoE");
            return (Criteria) this;
        }

        public Criteria andInfoENotIn(List<String> values) {
            addCriterion("INFO_E not in", values, "infoE");
            return (Criteria) this;
        }

        public Criteria andInfoEBetween(String value1, String value2) {
            addCriterion("INFO_E between", value1, value2, "infoE");
            return (Criteria) this;
        }

        public Criteria andInfoENotBetween(String value1, String value2) {
            addCriterion("INFO_E not between", value1, value2, "infoE");
            return (Criteria) this;
        }

        public Criteria andInfoInt1IsNull() {
            addCriterion("INFO_INT_1 is null");
            return (Criteria) this;
        }

        public Criteria andInfoInt1IsNotNull() {
            addCriterion("INFO_INT_1 is not null");
            return (Criteria) this;
        }

        public Criteria andInfoInt1EqualTo(Integer value) {
            addCriterion("INFO_INT_1 =", value, "infoInt1");
            return (Criteria) this;
        }

        public Criteria andInfoInt1NotEqualTo(Integer value) {
            addCriterion("INFO_INT_1 <>", value, "infoInt1");
            return (Criteria) this;
        }

        public Criteria andInfoInt1GreaterThan(Integer value) {
            addCriterion("INFO_INT_1 >", value, "infoInt1");
            return (Criteria) this;
        }

        public Criteria andInfoInt1GreaterThanOrEqualTo(Integer value) {
            addCriterion("INFO_INT_1 >=", value, "infoInt1");
            return (Criteria) this;
        }

        public Criteria andInfoInt1LessThan(Integer value) {
            addCriterion("INFO_INT_1 <", value, "infoInt1");
            return (Criteria) this;
        }

        public Criteria andInfoInt1LessThanOrEqualTo(Integer value) {
            addCriterion("INFO_INT_1 <=", value, "infoInt1");
            return (Criteria) this;
        }

        public Criteria andInfoInt1In(List<Integer> values) {
            addCriterion("INFO_INT_1 in", values, "infoInt1");
            return (Criteria) this;
        }

        public Criteria andInfoInt1NotIn(List<Integer> values) {
            addCriterion("INFO_INT_1 not in", values, "infoInt1");
            return (Criteria) this;
        }

        public Criteria andInfoInt1Between(Integer value1, Integer value2) {
            addCriterion("INFO_INT_1 between", value1, value2, "infoInt1");
            return (Criteria) this;
        }

        public Criteria andInfoInt1NotBetween(Integer value1, Integer value2) {
            addCriterion("INFO_INT_1 not between", value1, value2, "infoInt1");
            return (Criteria) this;
        }

        public Criteria andInfoInt2IsNull() {
            addCriterion("INFO_INT_2 is null");
            return (Criteria) this;
        }

        public Criteria andInfoInt2IsNotNull() {
            addCriterion("INFO_INT_2 is not null");
            return (Criteria) this;
        }

        public Criteria andInfoInt2EqualTo(Integer value) {
            addCriterion("INFO_INT_2 =", value, "infoInt2");
            return (Criteria) this;
        }

        public Criteria andInfoInt2NotEqualTo(Integer value) {
            addCriterion("INFO_INT_2 <>", value, "infoInt2");
            return (Criteria) this;
        }

        public Criteria andInfoInt2GreaterThan(Integer value) {
            addCriterion("INFO_INT_2 >", value, "infoInt2");
            return (Criteria) this;
        }

        public Criteria andInfoInt2GreaterThanOrEqualTo(Integer value) {
            addCriterion("INFO_INT_2 >=", value, "infoInt2");
            return (Criteria) this;
        }

        public Criteria andInfoInt2LessThan(Integer value) {
            addCriterion("INFO_INT_2 <", value, "infoInt2");
            return (Criteria) this;
        }

        public Criteria andInfoInt2LessThanOrEqualTo(Integer value) {
            addCriterion("INFO_INT_2 <=", value, "infoInt2");
            return (Criteria) this;
        }

        public Criteria andInfoInt2In(List<Integer> values) {
            addCriterion("INFO_INT_2 in", values, "infoInt2");
            return (Criteria) this;
        }

        public Criteria andInfoInt2NotIn(List<Integer> values) {
            addCriterion("INFO_INT_2 not in", values, "infoInt2");
            return (Criteria) this;
        }

        public Criteria andInfoInt2Between(Integer value1, Integer value2) {
            addCriterion("INFO_INT_2 between", value1, value2, "infoInt2");
            return (Criteria) this;
        }

        public Criteria andInfoInt2NotBetween(Integer value1, Integer value2) {
            addCriterion("INFO_INT_2 not between", value1, value2, "infoInt2");
            return (Criteria) this;
        }

        public Criteria andLogInfoIsNull() {
            addCriterion("LOG_INFO is null");
            return (Criteria) this;
        }

        public Criteria andLogInfoIsNotNull() {
            addCriterion("LOG_INFO is not null");
            return (Criteria) this;
        }

        public Criteria andLogInfoEqualTo(String value) {
            addCriterion("LOG_INFO =", value, "logInfo");
            return (Criteria) this;
        }

        public Criteria andLogInfoNotEqualTo(String value) {
            addCriterion("LOG_INFO <>", value, "logInfo");
            return (Criteria) this;
        }

        public Criteria andLogInfoGreaterThan(String value) {
            addCriterion("LOG_INFO >", value, "logInfo");
            return (Criteria) this;
        }

        public Criteria andLogInfoGreaterThanOrEqualTo(String value) {
            addCriterion("LOG_INFO >=", value, "logInfo");
            return (Criteria) this;
        }

        public Criteria andLogInfoLessThan(String value) {
            addCriterion("LOG_INFO <", value, "logInfo");
            return (Criteria) this;
        }

        public Criteria andLogInfoLessThanOrEqualTo(String value) {
            addCriterion("LOG_INFO <=", value, "logInfo");
            return (Criteria) this;
        }

        public Criteria andLogInfoLike(String value) {
            addCriterion("LOG_INFO like", value, "logInfo");
            return (Criteria) this;
        }

        public Criteria andLogInfoNotLike(String value) {
            addCriterion("LOG_INFO not like", value, "logInfo");
            return (Criteria) this;
        }

        public Criteria andLogInfoIn(List<String> values) {
            addCriterion("LOG_INFO in", values, "logInfo");
            return (Criteria) this;
        }

        public Criteria andLogInfoNotIn(List<String> values) {
            addCriterion("LOG_INFO not in", values, "logInfo");
            return (Criteria) this;
        }

        public Criteria andLogInfoBetween(String value1, String value2) {
            addCriterion("LOG_INFO between", value1, value2, "logInfo");
            return (Criteria) this;
        }

        public Criteria andLogInfoNotBetween(String value1, String value2) {
            addCriterion("LOG_INFO not between", value1, value2, "logInfo");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task_info
     *
     * @mbggenerated do_not_delete_during_merge Fri Feb 17 11:19:29 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}