package com.xxx.collect.base.model;

import java.io.Serializable;

public class TaskInfoKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.TASK_NAME
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.INFO_ID
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private String infoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.TASK_NAME
     *
     * @return the value of task_info.TASK_NAME
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.TASK_NAME
     *
     * @param taskName the value for task_info.TASK_NAME
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.INFO_ID
     *
     * @return the value of task_info.INFO_ID
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public String getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.INFO_ID
     *
     * @param infoId the value for task_info.INFO_ID
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setInfoId(String infoId) {
        this.infoId = infoId == null ? null : infoId.trim();
    }
}