package com.xxx.collect.base.model;

import java.io.Serializable;
import java.util.Date;

public class TaskInfo extends TaskInfoKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.BANCH
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private Long banch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.STATUS
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.START_DATE
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private String startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.END_DATE
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.SUCC_NUM
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private Long succNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.ERRO_NUM
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private Long erroNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.INFO_A
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private String infoA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.INFO_B
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private String infoB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.INFO_C
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private String infoC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.INFO_D
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private String infoD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.INFO_E
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private String infoE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.INFO_INT_1
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private Integer infoInt1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.INFO_INT_2
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private Integer infoInt2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.LOG_INFO
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private String logInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.CREATE_TIME
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.BANCH
     *
     * @return the value of task_info.BANCH
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public Long getBanch() {
        return banch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.BANCH
     *
     * @param banch the value for task_info.BANCH
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setBanch(Long banch) {
        this.banch = banch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.STATUS
     *
     * @return the value of task_info.STATUS
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.STATUS
     *
     * @param status the value for task_info.STATUS
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.START_DATE
     *
     * @return the value of task_info.START_DATE
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.START_DATE
     *
     * @param startDate the value for task_info.START_DATE
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.END_DATE
     *
     * @return the value of task_info.END_DATE
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.END_DATE
     *
     * @param endDate the value for task_info.END_DATE
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.SUCC_NUM
     *
     * @return the value of task_info.SUCC_NUM
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public Long getSuccNum() {
        return succNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.SUCC_NUM
     *
     * @param succNum the value for task_info.SUCC_NUM
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setSuccNum(Long succNum) {
        this.succNum = succNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.ERRO_NUM
     *
     * @return the value of task_info.ERRO_NUM
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public Long getErroNum() {
        return erroNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.ERRO_NUM
     *
     * @param erroNum the value for task_info.ERRO_NUM
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setErroNum(Long erroNum) {
        this.erroNum = erroNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.INFO_A
     *
     * @return the value of task_info.INFO_A
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public String getInfoA() {
        return infoA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.INFO_A
     *
     * @param infoA the value for task_info.INFO_A
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setInfoA(String infoA) {
        this.infoA = infoA == null ? null : infoA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.INFO_B
     *
     * @return the value of task_info.INFO_B
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public String getInfoB() {
        return infoB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.INFO_B
     *
     * @param infoB the value for task_info.INFO_B
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setInfoB(String infoB) {
        this.infoB = infoB == null ? null : infoB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.INFO_C
     *
     * @return the value of task_info.INFO_C
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public String getInfoC() {
        return infoC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.INFO_C
     *
     * @param infoC the value for task_info.INFO_C
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setInfoC(String infoC) {
        this.infoC = infoC == null ? null : infoC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.INFO_D
     *
     * @return the value of task_info.INFO_D
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public String getInfoD() {
        return infoD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.INFO_D
     *
     * @param infoD the value for task_info.INFO_D
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setInfoD(String infoD) {
        this.infoD = infoD == null ? null : infoD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.INFO_E
     *
     * @return the value of task_info.INFO_E
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public String getInfoE() {
        return infoE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.INFO_E
     *
     * @param infoE the value for task_info.INFO_E
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setInfoE(String infoE) {
        this.infoE = infoE == null ? null : infoE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.INFO_INT_1
     *
     * @return the value of task_info.INFO_INT_1
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public Integer getInfoInt1() {
        return infoInt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.INFO_INT_1
     *
     * @param infoInt1 the value for task_info.INFO_INT_1
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setInfoInt1(Integer infoInt1) {
        this.infoInt1 = infoInt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.INFO_INT_2
     *
     * @return the value of task_info.INFO_INT_2
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public Integer getInfoInt2() {
        return infoInt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.INFO_INT_2
     *
     * @param infoInt2 the value for task_info.INFO_INT_2
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setInfoInt2(Integer infoInt2) {
        this.infoInt2 = infoInt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.LOG_INFO
     *
     * @return the value of task_info.LOG_INFO
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public String getLogInfo() {
        return logInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.LOG_INFO
     *
     * @param logInfo the value for task_info.LOG_INFO
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setLogInfo(String logInfo) {
        this.logInfo = logInfo == null ? null : logInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.CREATE_TIME
     *
     * @return the value of task_info.CREATE_TIME
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.CREATE_TIME
     *
     * @param createTime the value for task_info.CREATE_TIME
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}