package com.xxx.collect.base.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TranslateInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table translate_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table translate_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table translate_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table translate_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public TranslateInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table translate_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table translate_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table translate_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table translate_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table translate_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table translate_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table translate_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table translate_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table translate_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table translate_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table translate_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWordIsNull() {
            addCriterion("word is null");
            return (Criteria) this;
        }

        public Criteria andWordIsNotNull() {
            addCriterion("word is not null");
            return (Criteria) this;
        }

        public Criteria andWordEqualTo(String value) {
            addCriterion("word =", value, "word");
            return (Criteria) this;
        }

        public Criteria andWordNotEqualTo(String value) {
            addCriterion("word <>", value, "word");
            return (Criteria) this;
        }

        public Criteria andWordGreaterThan(String value) {
            addCriterion("word >", value, "word");
            return (Criteria) this;
        }

        public Criteria andWordGreaterThanOrEqualTo(String value) {
            addCriterion("word >=", value, "word");
            return (Criteria) this;
        }

        public Criteria andWordLessThan(String value) {
            addCriterion("word <", value, "word");
            return (Criteria) this;
        }

        public Criteria andWordLessThanOrEqualTo(String value) {
            addCriterion("word <=", value, "word");
            return (Criteria) this;
        }

        public Criteria andWordLike(String value) {
            addCriterion("word like", value, "word");
            return (Criteria) this;
        }

        public Criteria andWordNotLike(String value) {
            addCriterion("word not like", value, "word");
            return (Criteria) this;
        }

        public Criteria andWordIn(List<String> values) {
            addCriterion("word in", values, "word");
            return (Criteria) this;
        }

        public Criteria andWordNotIn(List<String> values) {
            addCriterion("word not in", values, "word");
            return (Criteria) this;
        }

        public Criteria andWordBetween(String value1, String value2) {
            addCriterion("word between", value1, value2, "word");
            return (Criteria) this;
        }

        public Criteria andWordNotBetween(String value1, String value2) {
            addCriterion("word not between", value1, value2, "word");
            return (Criteria) this;
        }

        public Criteria andCwordIsNull() {
            addCriterion("cword is null");
            return (Criteria) this;
        }

        public Criteria andCwordIsNotNull() {
            addCriterion("cword is not null");
            return (Criteria) this;
        }

        public Criteria andCwordEqualTo(String value) {
            addCriterion("cword =", value, "cword");
            return (Criteria) this;
        }

        public Criteria andCwordNotEqualTo(String value) {
            addCriterion("cword <>", value, "cword");
            return (Criteria) this;
        }

        public Criteria andCwordGreaterThan(String value) {
            addCriterion("cword >", value, "cword");
            return (Criteria) this;
        }

        public Criteria andCwordGreaterThanOrEqualTo(String value) {
            addCriterion("cword >=", value, "cword");
            return (Criteria) this;
        }

        public Criteria andCwordLessThan(String value) {
            addCriterion("cword <", value, "cword");
            return (Criteria) this;
        }

        public Criteria andCwordLessThanOrEqualTo(String value) {
            addCriterion("cword <=", value, "cword");
            return (Criteria) this;
        }

        public Criteria andCwordLike(String value) {
            addCriterion("cword like", value, "cword");
            return (Criteria) this;
        }

        public Criteria andCwordNotLike(String value) {
            addCriterion("cword not like", value, "cword");
            return (Criteria) this;
        }

        public Criteria andCwordIn(List<String> values) {
            addCriterion("cword in", values, "cword");
            return (Criteria) this;
        }

        public Criteria andCwordNotIn(List<String> values) {
            addCriterion("cword not in", values, "cword");
            return (Criteria) this;
        }

        public Criteria andCwordBetween(String value1, String value2) {
            addCriterion("cword between", value1, value2, "cword");
            return (Criteria) this;
        }

        public Criteria andCwordNotBetween(String value1, String value2) {
            addCriterion("cword not between", value1, value2, "cword");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTranslateModelIsNull() {
            addCriterion("translate_model is null");
            return (Criteria) this;
        }

        public Criteria andTranslateModelIsNotNull() {
            addCriterion("translate_model is not null");
            return (Criteria) this;
        }

        public Criteria andTranslateModelEqualTo(Integer value) {
            addCriterion("translate_model =", value, "translateModel");
            return (Criteria) this;
        }

        public Criteria andTranslateModelNotEqualTo(Integer value) {
            addCriterion("translate_model <>", value, "translateModel");
            return (Criteria) this;
        }

        public Criteria andTranslateModelGreaterThan(Integer value) {
            addCriterion("translate_model >", value, "translateModel");
            return (Criteria) this;
        }

        public Criteria andTranslateModelGreaterThanOrEqualTo(Integer value) {
            addCriterion("translate_model >=", value, "translateModel");
            return (Criteria) this;
        }

        public Criteria andTranslateModelLessThan(Integer value) {
            addCriterion("translate_model <", value, "translateModel");
            return (Criteria) this;
        }

        public Criteria andTranslateModelLessThanOrEqualTo(Integer value) {
            addCriterion("translate_model <=", value, "translateModel");
            return (Criteria) this;
        }

        public Criteria andTranslateModelIn(List<Integer> values) {
            addCriterion("translate_model in", values, "translateModel");
            return (Criteria) this;
        }

        public Criteria andTranslateModelNotIn(List<Integer> values) {
            addCriterion("translate_model not in", values, "translateModel");
            return (Criteria) this;
        }

        public Criteria andTranslateModelBetween(Integer value1, Integer value2) {
            addCriterion("translate_model between", value1, value2, "translateModel");
            return (Criteria) this;
        }

        public Criteria andTranslateModelNotBetween(Integer value1, Integer value2) {
            addCriterion("translate_model not between", value1, value2, "translateModel");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table translate_info
     *
     * @mbggenerated do_not_delete_during_merge Fri Feb 17 11:19:30 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table translate_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}