package com.xxx.collect.base.model;

import java.io.Serializable;

public class TranslateCacheKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column translate_cache.engine
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private String engine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column translate_cache.mode
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private Integer mode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column translate_cache.src
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private String src;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column translate_cache.rest
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private String rest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table translate_cache
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column translate_cache.engine
     *
     * @return the value of translate_cache.engine
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public String getEngine() {
        return engine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column translate_cache.engine
     *
     * @param engine the value for translate_cache.engine
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setEngine(String engine) {
        this.engine = engine == null ? null : engine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column translate_cache.mode
     *
     * @return the value of translate_cache.mode
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public Integer getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column translate_cache.mode
     *
     * @param mode the value for translate_cache.mode
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setMode(Integer mode) {
        this.mode = mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column translate_cache.src
     *
     * @return the value of translate_cache.src
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column translate_cache.src
     *
     * @param src the value for translate_cache.src
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column translate_cache.rest
     *
     * @return the value of translate_cache.rest
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public String getRest() {
        return rest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column translate_cache.rest
     *
     * @param rest the value for translate_cache.rest
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setRest(String rest) {
        this.rest = rest == null ? null : rest.trim();
    }
}