package com.xxx.collect.base.model;

import java.io.Serializable;
import java.util.Date;

public class TranslateInfo extends TranslateInfoKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column translate_info.type
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column translate_info.translate_model
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private Integer translateModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column translate_info.create_time
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table translate_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column translate_info.type
     *
     * @return the value of translate_info.type
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column translate_info.type
     *
     * @param type the value for translate_info.type
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column translate_info.translate_model
     *
     * @return the value of translate_info.translate_model
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public Integer getTranslateModel() {
        return translateModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column translate_info.translate_model
     *
     * @param translateModel the value for translate_info.translate_model
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setTranslateModel(Integer translateModel) {
        this.translateModel = translateModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column translate_info.create_time
     *
     * @return the value of translate_info.create_time
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column translate_info.create_time
     *
     * @param createTime the value for translate_info.create_time
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}