package com.xxx.collect.base.model;

import java.io.Serializable;
import java.util.Date;

public class TranslateCache extends TranslateCacheKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column translate_cache.use_count
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private Integer useCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column translate_cache.create_time
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column translate_cache.is_audit
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private Boolean isAudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column translate_cache.has_audit
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private Boolean hasAudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table translate_cache
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column translate_cache.use_count
     *
     * @return the value of translate_cache.use_count
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public Integer getUseCount() {
        return useCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column translate_cache.use_count
     *
     * @param useCount the value for translate_cache.use_count
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setUseCount(Integer useCount) {
        this.useCount = useCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column translate_cache.create_time
     *
     * @return the value of translate_cache.create_time
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column translate_cache.create_time
     *
     * @param createTime the value for translate_cache.create_time
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column translate_cache.is_audit
     *
     * @return the value of translate_cache.is_audit
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public Boolean getIsAudit() {
        return isAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column translate_cache.is_audit
     *
     * @param isAudit the value for translate_cache.is_audit
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setIsAudit(Boolean isAudit) {
        this.isAudit = isAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column translate_cache.has_audit
     *
     * @return the value of translate_cache.has_audit
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public Boolean getHasAudit() {
        return hasAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column translate_cache.has_audit
     *
     * @param hasAudit the value for translate_cache.has_audit
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setHasAudit(Boolean hasAudit) {
        this.hasAudit = hasAudit;
    }
}