package com.xxx.collect.base.model;

import java.io.Serializable;

public class TranslateInfoKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column translate_info.word
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private String word;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column translate_info.cword
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private String cword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table translate_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column translate_info.word
     *
     * @return the value of translate_info.word
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column translate_info.word
     *
     * @param word the value for translate_info.word
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column translate_info.cword
     *
     * @return the value of translate_info.cword
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public String getCword() {
        return cword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column translate_info.cword
     *
     * @param cword the value for translate_info.cword
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    public void setCword(String cword) {
        this.cword = cword == null ? null : cword.trim();
    }
}