package com.xxx.collect.core.db.dbmapper;

import com.xxx.collect.core.db.dbmodel.ProxyInfo;
import com.xxx.collect.core.db.dbmodel.ProxyInfoExample;
import com.xxx.collect.core.db.dbmodel.ProxyInfoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProxyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_info
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    int countByExample(ProxyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_info
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    int deleteByExample(ProxyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_info
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    int deleteByPrimaryKey(ProxyInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_info
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    int insert(ProxyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_info
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    int insertSelective(ProxyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_info
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    List<ProxyInfo> selectByExample(ProxyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_info
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    ProxyInfo selectByPrimaryKey(ProxyInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_info
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProxyInfo record, @Param("example") ProxyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_info
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    int updateByExample(@Param("record") ProxyInfo record, @Param("example") ProxyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_info
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    int updateByPrimaryKeySelective(ProxyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_info
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    int updateByPrimaryKey(ProxyInfo record);
}