package com.xxx.collect.core.db.dbmapper;

import com.xxx.collect.core.db.dbmodel.TaskLock;
import com.xxx.collect.core.db.dbmodel.TaskLockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskLockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_lock
     *
     * @mbggenerated Thu Aug 25 10:46:02 CST 2016
     */
    int countByExample(TaskLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_lock
     *
     * @mbggenerated Thu Aug 25 10:46:02 CST 2016
     */
    int deleteByExample(TaskLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_lock
     *
     * @mbggenerated Thu Aug 25 10:46:02 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_lock
     *
     * @mbggenerated Thu Aug 25 10:46:02 CST 2016
     */
    int insert(TaskLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_lock
     *
     * @mbggenerated Thu Aug 25 10:46:02 CST 2016
     */
    int insertSelective(TaskLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_lock
     *
     * @mbggenerated Thu Aug 25 10:46:02 CST 2016
     */
    List<TaskLock> selectByExample(TaskLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_lock
     *
     * @mbggenerated Thu Aug 25 10:46:02 CST 2016
     */
    TaskLock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_lock
     *
     * @mbggenerated Thu Aug 25 10:46:02 CST 2016
     */
    int updateByExampleSelective(@Param("record") TaskLock record, @Param("example") TaskLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_lock
     *
     * @mbggenerated Thu Aug 25 10:46:02 CST 2016
     */
    int updateByExample(@Param("record") TaskLock record, @Param("example") TaskLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_lock
     *
     * @mbggenerated Thu Aug 25 10:46:02 CST 2016
     */
    int updateByPrimaryKeySelective(TaskLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_lock
     *
     * @mbggenerated Thu Aug 25 10:46:02 CST 2016
     */
    int updateByPrimaryKey(TaskLock record);
}