package com.xxx.collect.core.db.dbmodel;

import java.io.Serializable;

public class ProxyInfo extends ProxyInfoKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxy_info.STATUS
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxy_info.SERIES_ERROR
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    private Integer seriesError;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxy_info.LAST_USE
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    private Short lastUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proxy_info
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_info.STATUS
     *
     * @return the value of proxy_info.STATUS
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_info.STATUS
     *
     * @param status the value for proxy_info.STATUS
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_info.SERIES_ERROR
     *
     * @return the value of proxy_info.SERIES_ERROR
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    public Integer getSeriesError() {
        return seriesError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_info.SERIES_ERROR
     *
     * @param seriesError the value for proxy_info.SERIES_ERROR
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    public void setSeriesError(Integer seriesError) {
        this.seriesError = seriesError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_info.LAST_USE
     *
     * @return the value of proxy_info.LAST_USE
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    public Short getLastUse() {
        return lastUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_info.LAST_USE
     *
     * @param lastUse the value for proxy_info.LAST_USE
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    public void setLastUse(Short lastUse) {
        this.lastUse = lastUse;
    }
}