package com.xxx.collect.core.db.dbmodel;

import java.io.Serializable;

public class ProxyInfoKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxy_info.IP
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxy_info.PORT
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    private Integer port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proxy_info
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_info.IP
     *
     * @return the value of proxy_info.IP
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_info.IP
     *
     * @param ip the value for proxy_info.IP
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_info.PORT
     *
     * @return the value of proxy_info.PORT
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_info.PORT
     *
     * @param port the value for proxy_info.PORT
     *
     * @mbggenerated Thu Nov 26 22:12:36 CST 2015
     */
    public void setPort(Integer port) {
        this.port = port;
    }
}