package com.xxx.collect.base.dao;

import com.xxx.collect.base.model.ErrorLog;
import com.xxx.collect.base.model.ErrorLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ErrorLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int countByExample(ErrorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int deleteByExample(ErrorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int insert(ErrorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int insertSelective(ErrorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    List<ErrorLog> selectByExampleWithRowbounds(ErrorLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    List<ErrorLog> selectByExample(ErrorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int updateByExampleSelective(@Param("record") ErrorLog record, @Param("example") ErrorLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_log
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int updateByExample(@Param("record") ErrorLog record, @Param("example") ErrorLogExample example);
}