package com.xxx.collect.base.dao;

import com.xxx.collect.base.model.LangInfo;
import com.xxx.collect.base.model.LangInfoExample;
import com.xxx.collect.base.model.LangInfoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LangInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lang_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    int countByExample(LangInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lang_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    int deleteByExample(LangInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lang_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    int deleteByPrimaryKey(LangInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lang_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    int insert(LangInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lang_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    int insertSelective(LangInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lang_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    List<LangInfo> selectByExampleWithRowbounds(LangInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lang_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    List<LangInfo> selectByExample(LangInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lang_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    LangInfo selectByPrimaryKey(LangInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lang_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    int updateByExampleSelective(@Param("record") LangInfo record, @Param("example") LangInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lang_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    int updateByExample(@Param("record") LangInfo record, @Param("example") LangInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lang_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    int updateByPrimaryKeySelective(LangInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lang_info
     *
     * @mbggenerated Fri Feb 17 11:19:30 CST 2017
     */
    int updateByPrimaryKey(LangInfo record);
}