package com.xxx.collect.base.dao;

import com.xxx.collect.base.model.SpiderItemInfo;
import com.xxx.collect.base.model.SpiderItemInfoExample;
import com.xxx.collect.base.model.SpiderItemInfoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SpiderItemInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_item_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int countByExample(SpiderItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_item_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int deleteByExample(SpiderItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_item_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int deleteByPrimaryKey(SpiderItemInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_item_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int insert(SpiderItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_item_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int insertSelective(SpiderItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_item_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    List<SpiderItemInfo> selectByExampleWithRowbounds(SpiderItemInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_item_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    List<SpiderItemInfo> selectByExample(SpiderItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_item_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    SpiderItemInfo selectByPrimaryKey(SpiderItemInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_item_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int updateByExampleSelective(@Param("record") SpiderItemInfo record, @Param("example") SpiderItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_item_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int updateByExample(@Param("record") SpiderItemInfo record, @Param("example") SpiderItemInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_item_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int updateByPrimaryKeySelective(SpiderItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_item_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int updateByPrimaryKey(SpiderItemInfo record);
}