package com.xxx.collect.base.dao;

import com.xxx.collect.base.model.SpiderHtmlStore;
import com.xxx.collect.base.model.SpiderHtmlStoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SpiderHtmlStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_html_store
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int countByExample(SpiderHtmlStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_html_store
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int deleteByExample(SpiderHtmlStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_html_store
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int deleteByPrimaryKey(String url);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_html_store
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int insert(SpiderHtmlStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_html_store
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int insertSelective(SpiderHtmlStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_html_store
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    List<SpiderHtmlStore> selectByExampleWithBLOBsWithRowbounds(SpiderHtmlStoreExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_html_store
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    List<SpiderHtmlStore> selectByExampleWithBLOBs(SpiderHtmlStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_html_store
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    List<SpiderHtmlStore> selectByExampleWithRowbounds(SpiderHtmlStoreExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_html_store
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    List<SpiderHtmlStore> selectByExample(SpiderHtmlStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_html_store
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    SpiderHtmlStore selectByPrimaryKey(String url);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_html_store
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int updateByExampleSelective(@Param("record") SpiderHtmlStore record, @Param("example") SpiderHtmlStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_html_store
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") SpiderHtmlStore record, @Param("example") SpiderHtmlStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_html_store
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int updateByExample(@Param("record") SpiderHtmlStore record, @Param("example") SpiderHtmlStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_html_store
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int updateByPrimaryKeySelective(SpiderHtmlStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_html_store
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(SpiderHtmlStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_html_store
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int updateByPrimaryKey(SpiderHtmlStore record);
}