package com.xxx.collect.base.dao;

import com.xxx.collect.base.model.TaskInfo;
import com.xxx.collect.base.model.TaskInfoExample;
import com.xxx.collect.base.model.TaskInfoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TaskInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int countByExample(TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int deleteByExample(TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int deleteByPrimaryKey(TaskInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int insert(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int insertSelective(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    List<TaskInfo> selectByExampleWithRowbounds(TaskInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    List<TaskInfo> selectByExample(TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    TaskInfo selectByPrimaryKey(TaskInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int updateByExampleSelective(@Param("record") TaskInfo record, @Param("example") TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int updateByExample(@Param("record") TaskInfo record, @Param("example") TaskInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int updateByPrimaryKeySelective(TaskInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbggenerated Fri Feb 17 11:19:29 CST 2017
     */
    int updateByPrimaryKey(TaskInfo record);
}